# Generated by Django 5.1.2 on 2024-10-26 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=15, unique=True, verbose_name='License Plate')),
                ('brand', models.CharField(max_length=20, verbose_name='Brand')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id_owner', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('birth_date', models.DateTimeField(verbose_name='Birth Date')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10, unique=True, verbose_name='License Number')),
                ('license_type', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B'), ('C', 'Type C'), ('D', 'Type D'), ('M', 'Type M'), ('T', 'Type T')], max_length=1, verbose_name='License Type')),
                ('issue_date', models.DateTimeField(verbose_name='Issue Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='car_owners.owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'Licenses',
                'ordering': ['issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='car_owners.car', verbose_name='Car')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='car_owners.owner', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Ownership',
                'verbose_name_plural': 'Ownerships',
                'ordering': ['start_date'],
            },
        ),
    ]
