site_name: 'Отчёт Web-программирование домашнее задание 1'
theme:
  name: 'material'
nav:
  - Главная: index.md
  - Задание 1: chapter1.md
  - Задание 2: chapter2.md
  - Задание 3: chapter3.md
  - Задание 4: chapter4.md
  - Задание 5: chapter5.md
