# Generated by Django 5.1.2 on 2024-11-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_remove_user_address_remove_user_nationality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
