# Generated by Django 5.1.2 on 2024-11-27 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_num', models.CharField(max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('type', models.CharField(max_length=30, verbose_name='Тип автобуса')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('status', models.CharField(choices=[('Свободен', 'Свободен'), ('В ремонте', 'В ремонте'), ('Занят', 'Занят')], max_length=30, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_num', models.PositiveIntegerField(unique=True, verbose_name='Номер маршрута')),
                ('start_point', models.CharField(max_length=30, verbose_name='Начальный пункт')),
                ('end_point', models.CharField(max_length=30, verbose_name='Конечный пункт')),
                ('start_time', models.TimeField(verbose_name='Время начала движения')),
                ('end_time', models.TimeField(verbose_name='Время конца движения')),
                ('interval', models.PositiveIntegerField(verbose_name='Интервал движения (мин.)')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (мин.)')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата обслуживания')),
                ('reason', models.CharField(max_length=30, verbose_name='Причина')),
                ('status', models.CharField(choices=[('В процессе', 'В процессе'), ('Починен', 'Починен')], max_length=30, verbose_name='Статус')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.bus', verbose_name='Автобус')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Паспортные данные')),
                ('driver_class', models.CharField(max_length=20, verbose_name='Класс водителя')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж работы (лет)')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оклад')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('status', models.CharField(choices=[('На работе', 'На работе'), ('Выходной', 'Выходной'), ('В отпуске', 'В отпуске'), ('На больничном', 'На больничном'), ('В командировке', 'В командировке')], max_length=30, verbose_name='Статус')),
                ('routes', models.ManyToManyField(related_name='drivers', to='bus_app.route', verbose_name='Маршруты')),
            ],
        ),
        migrations.CreateModel(
            name='BusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.bus', verbose_name='Автобус')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.route', verbose_name='Маршрут')),
            ],
        ),
        migrations.CreateModel(
            name='DriverSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Дата работы')),
                ('shift_start', models.TimeField(verbose_name='Начало смены')),
                ('shift_end', models.TimeField(verbose_name='Конец смены')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.bus', verbose_name='Автобус')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.driver', verbose_name='Водитель')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_app.route', verbose_name='Маршрут')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'bus', 'route', 'work_date'), name='unique_schedule_entry')],
            },
        ),
    ]
