# Generated by Django 5.1.4 on 2024-12-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_customuser_userprofile'),
        ('booking', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookings',
            field=models.ManyToManyField(related_name='user_profile', to='booking.booking'),
        ),
    ]
