# Generated by Django 5.1.4 on 2024-12-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_bookings'),
        ('booking', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookings',
            field=models.ManyToManyField(related_name='user_profile', to='booking.booking', verbose_name='Брони'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff_member',
            field=models.BooleanField(default=False, verbose_name='Сотрудник отеля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта'),
        ),
    ]
