# Generated by Django 4.2.20 on 2025-03-06 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_owner',
            field=models.ManyToManyField(related_name='owned_cars', through='project_first_app.Ownership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(related_name='owners', through='project_first_app.Ownership', to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_licenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to=settings.AUTH_USER_MODEL),
        ),
    ]
