site_name: Web Labs Documentation
nav:
  - Home: index.md
  - Lab 1:
      - "Task 1": lab-1/task1.md
      - "Task 2": lab-1/task2.md
      - "Task 3": lab-1/task3.md
      - "Task 4": lab-1/task4.md
      - "Task 5": lab-1/task5.md

theme:
  name: material
