site_name: WEB-programming
nav:
  - Home: index.md
  - 1 lab:
      - Task 1: lw1/1.md
      - Task 2: lw1/2.md
      - Task 3: lw1/3.md
      - Task 4: lw1/4.md
      - Task 5: lw1/5.md
theme:
  name: bootstrap4