# Generated by Django 5.1.2 on 2024-11-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="race",
            name="participants",
            field=models.ManyToManyField(related_name="races", to="race_app.racer"),
        ),
    ]