# Generated by Django 5.1.3 on 2024-11-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
