# Generated by Django 3.1.2 on 2020-10-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
