# Generated by Django 5.1.4 on 2025-01-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='age_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='concert',
            name='status',
            field=models.CharField(choices=[('held', 'Проведен'), ('cancelled', 'Отменен'), ('prepared', 'Подготовлен'), ('in_progress', 'В работе')], default='in_progress', max_length=11),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждено'), ('pending', 'В ожидании'), ('returned', 'Возврат')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
