# Generated by Django 5.1.2 on 2024-11-02 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Race",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("dt_event", models.DateField()),
                ("dt_due_register", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Racer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("PQ", "partnership question"),
                            ("RQ", "race question"),
                            ("ot", "other question"),
                        ],
                        default="other question",
                        max_length=20,
                    ),
                ),
                ("header", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("rating", models.IntegerField()),
                ("dt_written", models.DateTimeField(auto_now_add=True)),
                (
                    "race",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_panel.race",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_panel.racer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("license_plate", models.CharField(max_length=100)),
                ("info", models.TextField()),
                (
                    "car_owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="race_panel.racer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RaceTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tour_num", models.IntegerField()),
                ("n_laps", models.IntegerField()),
                ("time", models.IntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_panel.race",
                    ),
                ),
                (
                    "racer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_panel.racer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt_register", models.DateTimeField(auto_now_add=True)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="race_panel.car"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_panel.race",
                    ),
                ),
                (
                    "racer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_panel.racer",
                    ),
                ),
            ],
        ),
    ]
