# Generated by Django 5.1.4 on 2024-12-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('room_category', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('night_cost', models.IntegerField(default=0)),
                ('guest_count', models.IntegerField(default=2)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
    ]
