# Generated by Django 5.1.4 on 2024-12-30 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fix_date', models.DateField(auto_now=True)),
                ('clean_date', models.DateField(auto_now=True)),
                ('rooms_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Этаж',
                'verbose_name_plural': 'Этажи',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('guest_count', models.IntegerField(default=2)),
                ('description', models.CharField(max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.floor')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
    ]
