# Generated by Django 5.1.4 on 2025-01-08 11:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.TextField(blank=True)),
                ('contact_info', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Captain', 'Captain'), ('Co-Pilot', 'Co-Pilot'), ('Navigator', 'Navigator'), ('Attendant', 'Attendant')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('seats_capacity', models.IntegerField()),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('airline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='airline_app.airline')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendants', models.ManyToManyField(related_name='attendant_in', to='airline_app.crewmember')),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captain_of', to='airline_app.crewmember')),
                ('co_pilot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_pilot_of', to='airline_app.crewmember')),
                ('navigator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigator_of', to='airline_app.crewmember')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('education', models.CharField(max_length=255)),
                ('work_experience_years', models.IntegerField()),
                ('passport_data', models.CharField(max_length=20)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='airline_app.airline')),
            ],
        ),
        migrations.AddField(
            model_name='crewmember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_roles', to='airline_app.employee'),
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='airline_app.airline')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='airline_app.planemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='airline_app.plane')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('arrival_day', models.IntegerField(default=0)),
                ('distance_km', models.FloatField()),
                ('regularity', models.CharField(max_length=20)),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_routes', to='airline_app.airport')),
                ('destination_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='airline_app.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('sold_tickets_number', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Boarding', 'Boarding'), ('Boarding Complete', 'Boarding Complete'), ('In Air', 'In Air'), ('Landing', 'Landing'), ('Complete', 'Complete'), ('Delayed', 'Delayed'), ('Canceled', 'Canceled')], default='Scheduled', max_length=50)),
                ('crew', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airline_app.crew')),
                ('plane', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights', to='airline_app.plane')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='airline_app.route')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('is_sold', models.BooleanField(default=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airline_app.flight')),
            ],
        ),
        migrations.CreateModel(
            name='TransitStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('arrival_day', models.IntegerField(default=0)),
                ('departure_time', models.TimeField()),
                ('departure_day', models.IntegerField(default=0)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_stops', to='airline_app.airport')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_stops', to='airline_app.route')),
            ],
        ),
    ]
