# Generated by Django 5.1.2 on 2025-02-24 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0002_floor_alter_floorschedule_floor_alter_room_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='floors',
        ),
        migrations.AlterField(
            model_name='stayhistory',
            name='check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CleaningAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_assignments', to='hostel_app.employee')),
                ('floor_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_assignments', to='hostel_app.floorschedule')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_reports', to='hostel_app.room')),
            ],
        ),
    ]
