# Generated by Django 5.1.2 on 2025-02-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0003_remove_employee_floors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelIncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('quarter', models.PositiveIntegerField()),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='incomereport',
            name='client_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='check_in_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stayhistory',
            name='check_in_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stayhistory',
            name='check_out_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
