# Generated by Django 5.1.2 on 2025-02-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0004_hotelincomereport_incomereport_client_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelIncomeReport',
        ),
        migrations.DeleteModel(
            name='IncomeReport',
        ),
    ]
