# Generated by Django 5.1.2 on 2025-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0005_delete_hotelincomereport_delete_incomereport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='room',
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_day',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
