# Generated by Django 5.1.2 on 2025-02-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0006_remove_client_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
