# Generated by Django 5.1.2 on 2025-02-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0007_alter_room_price_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
    ]
