# Generated by Django 5.1.2 on 2025-02-24 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0008_remove_employee_middle_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StayHistory',
            new_name='ClientRoom',
        ),
    ]
