# Generated by Django 5.1.2 on 2025-02-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0009_rename_stayhistory_clientroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientroom',
            name='count_of_clients',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
