# Generated by Django 5.1.2 on 2025-02-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_app', '0010_clientroom_count_of_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientroom',
            name='check_in_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
