# Generated by Django 5.1.2 on 2024-10-10 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conferences", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор конференции",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="members",
            field=models.ManyToManyField(
                related_name="conferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники конференции",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="conference",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="conferences.conference",
                verbose_name="Конференция",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор комментария",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="conference",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="conferences.conference",
                verbose_name="Котференция",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="conferences.room",
                verbose_name="Конференц зал",
            ),
        ),
    ]
