# Generated by Django 5.1.2 on 2024-10-10 15:14

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания комментария",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conference",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="conferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники конференции",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Рейтинг",
            ),
        ),
    ]
