# Generated by Django 5.1.2 on 2024-10-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Auto",
            new_name="Car",
        ),
        migrations.RenameField(
            model_name="ownership",
            old_name="id_auto",
            new_name="id_car",
        ),
        migrations.AlterField(
            model_name="license",
            name="receiving_date",
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ownership",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
