# Generated by Django 5.1.2 on 2024-10-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="address",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="owner",
            name="nationality",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="owner",
            name="passport",
            field=models.CharField(default="", max_length=30),
        ),
    ]
