# Generated by Django 5.1.3 on 2024-11-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("driving", "0003_alter_carowner_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carowner",
            name="user",
        ),
    ]
