# Generated by Django 5.1.3 on 2024-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driving", "0004_remove_carowner_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="issued_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
