# Generated by Django 5.1.3 on 2024-11-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("driving", "0005_alter_license_issued_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="driving.carowner",
            ),
        ),
    ]
