# Generated by Django 5.2.12 on 2026-03-13 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отдела')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='FeedingRation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Номер рациона')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рацион',
                'verbose_name_plural': 'Рационы',
            },
        ),
        migrations.CreateModel(
            name='FeedingRationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип рациона',
                'verbose_name_plural': 'Типы рационов',
            },
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название зоны')),
                ('continent', models.CharField(max_length=100, verbose_name='Материк')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('description', models.TextField(blank=True, verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Зона обитания',
                'verbose_name_plural': 'Зоны обитания',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_number', models.CharField(max_length=20, unique=True, verbose_name='Табельный номер')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('staff_type', models.CharField(choices=[('caretaker', 'Смотритель'), ('vet', 'Ветеринар')], max_length=10, verbose_name='Тип сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='WinteringPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название места')),
            ],
            options={
                'verbose_name': 'Место зимовки',
                'verbose_name_plural': 'Места зимовки',
            },
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название зоопарка')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Зоопарк',
                'verbose_name_plural': 'Зоопарки',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название здания')),
                ('building_type', models.CharField(choices=[('summer', 'Летнее'), ('winter', 'Зимнее')], max_length=10, verbose_name='Тип здания')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='main.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
            },
        ),
        migrations.CreateModel(
            name='Enclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер вольера')),
                ('is_communal', models.BooleanField(default=False, verbose_name='Коммунальная квартира')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Наличие бассейна')),
                ('has_equipment', models.BooleanField(default=False, verbose_name='Дополнительное оборудование')),
                ('has_indoor', models.BooleanField(default=False, verbose_name='Внутреннее помещение')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enclosures', to='main.building', verbose_name='Здание')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enclosures', to='main.department', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Вольер',
                'verbose_name_plural': 'Вольеры',
                'unique_together': {('department', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(max_length=50, unique=True, verbose_name='Уникальный номер')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Самец'), ('F', 'Самка')], max_length=1, verbose_name='Пол')),
                ('animal_type', models.CharField(choices=[('mammal', 'Млекопитающее'), ('bird', 'Птица'), ('reptile', 'Рептилия')], max_length=10, verbose_name='Тип животного')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата улета')),
                ('normal_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Нормальная температура')),
                ('hibernation_start', models.DateField(blank=True, null=True, verbose_name='Начало спячки')),
                ('hibernation_end', models.DateField(blank=True, null=True, verbose_name='Конец спячки')),
                ('ownership_type', models.CharField(choices=[('own', 'Собственность зоопарка'), ('lease', 'Аренда')], max_length=5, verbose_name='Тип собственности')),
                ('lease_start', models.DateField(blank=True, null=True, verbose_name='Начало аренды')),
                ('lease_end', models.DateField(blank=True, null=True, verbose_name='Окончание аренды')),
                ('lease_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость аренды')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('seller_organization', models.CharField(blank=True, max_length=200, verbose_name='Организация-продавец')),
                ('arrival_date', models.DateField(verbose_name='Дата поступления в зоопарк')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='main.department', verbose_name='Отдел')),
                ('current_enclosure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='main.enclosure', verbose_name='Текущий вольер')),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='main.habitat', verbose_name='Зона обитания')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='FeedingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_history', to='main.animal')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.feedingration')),
            ],
            options={
                'verbose_name': 'История кормления',
                'verbose_name_plural': 'Истории кормления',
            },
        ),
        migrations.AddField(
            model_name='feedingration',
            name='ration_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.feedingrationtype', verbose_name='Тип рациона'),
        ),
        migrations.CreateModel(
            name='CaretakerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animal')),
                ('caretaker', models.ForeignKey(limit_choices_to={'staff_type': 'caretaker'}, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'verbose_name': 'Назначение смотрителя',
                'verbose_name_plural': 'Назначения смотрителей',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='caretakers',
            field=models.ManyToManyField(limit_choices_to={'staff_type': 'caretaker'}, related_name='animals_cared', through='main.CaretakerAssignment', to='main.staff'),
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='main.animal')),
                ('from_enclosure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='main.enclosure')),
                ('to_enclosure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='main.enclosure')),
            ],
            options={
                'verbose_name': 'История пересадок',
                'verbose_name_plural': 'Истории пересадок',
            },
        ),
        migrations.CreateModel(
            name='VeterinarianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.animal')),
                ('veterinarian', models.ForeignKey(limit_choices_to={'staff_type': 'vet'}, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
            ],
            options={
                'verbose_name': 'Назначение ветеринара',
                'verbose_name_plural': 'Назначения ветеринаров',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='veterinarians',
            field=models.ManyToManyField(limit_choices_to={'staff_type': 'vet'}, related_name='animals_vetted', through='main.VeterinarianAssignment', to='main.staff'),
        ),
        migrations.AddField(
            model_name='animal',
            name='wintering_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.winteringplace', verbose_name='Место зимовки'),
        ),
        migrations.AddField(
            model_name='animal',
            name='owner_zoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leased_animals', to='main.zoo', verbose_name='Зоопарк-владелец (аренда)'),
        ),
    ]
