# Generated by Django 5.2.12 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прилёта'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата улёта'),
        ),
    ]
