# Generated by Django 4.2.16 on 2024-11-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_number", models.CharField(max_length=15)),
                ("brand", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("birth_date", models.DateField(null=True)),
                ("last_name", models.CharField(max_length=30)),
                ("first_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField()),
                ("date_end", models.DateField(null=True)),
                (
                    "car_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.car",
                    ),
                ),
                (
                    "owner_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.owner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="owner",
            name="cars",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.car"
            ),
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=10)),
                ("date_of_issue", models.DateField()),
                (
                    "owner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_first_app.owner",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="car_owner",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.owner"
            ),
        ),
    ]
