site_name: Отчет по заданиям
site_url: "https://lek1ch.github.io/ITMO_ICT_WebDevelopment_2024-2025"

nav:
  - Главная: docs/index.md
  - Задание 1: docs/task1.md
  - Задание 2: docs/task2.md
  - Задание 3: docs/task3.md
  - Задание 4: docs/task4.md
  - Задание 5: docs/task5.md

theme:
  name:  mkdocs


