# Generated by Django 5.1.6 on 2025-02-08 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id_auto', models.IntegerField(primary_key=True, serialize=False)),
                ('state_number', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AutoOwner',
            fields=[
                ('id_owner', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id_license', models.IntegerField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('date_of_issue', models.DateField()),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.autoowner')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id_ownership', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('id_auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.auto')),
                ('id_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_first_app.autoowner')),
            ],
        ),
    ]
