# Generated by Django 5.1.6 on 2025-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_autoowner_options_alter_autoowner_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='id_auto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autoowner',
            name='id_owner',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverlicense',
            name='id_license',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_ownership',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
