# Generated by Django 5.1.3 on 2024-11-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hh", "0002_company_skill_tag_cv_vacancy_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="content_blob",
            field=models.TextField(),
        ),
    ]
