# Generated by Django 5.1.7 on 2025-03-22 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='conference')),
                ('topic', models.CharField(blank=True, choices=[('business', 'business'), ('design', 'design'), ('physics', 'physics')], max_length=10, verbose_name='topic')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('description', models.CharField(max_length=200, verbose_name='conference description')),
                ('location_description', models.CharField(max_length=200, verbose_name='location description')),
                ('terms', models.CharField(max_length=1000, verbose_name='participation terms')),
                ('recommend', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, verbose_name='recommend')),
                ('speaker', models.ManyToManyField(related_name='speaker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conference',
                'verbose_name_plural': 'conferences',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='comment')),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='rating')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='comment author')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conf_app.conference', verbose_name='conference')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
