# Generated by Django 5.2.7 on 2025-10-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('plate_number', models.CharField(max_length=10, unique=True, verbose_name='Госномер')),
            ],
        ),
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('passport', models.CharField(max_length=10, unique=True, verbose_name='Паспорт')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Адрес')),
                ('nationality', models.CharField(blank=True, max_length=30, verbose_name='Национальность')),
            ],
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10, verbose_name='Номер удостоверения')),
                ('type', models.CharField(choices=[('A', 'Мотоциклы'), ('B', 'Легковые автомобили'), ('C', 'Грузовые автомобили'), ('D', 'Автобусы')], max_length=1, verbose_name='Тип')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner', verbose_name='Владелец')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала владения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания владения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.car', verbose_name='Автомобиль')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner', verbose_name='Владелец')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owners',
            field=models.ManyToManyField(through='project_first_app.Ownership', through_fields=('car', 'owner'), to='project_first_app.carowner', verbose_name='Владельцы'),
        ),
    ]
