# Generated by Django 5.1.3 on 2024-11-29 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=11)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('origin_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_employed', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_num', models.SmallIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rooms', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_employee', to='hotel_app.employee')),
                ('floor_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_floor', to='hotel_app.floor')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hotel_app.hotel'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], default='Single', max_length=6)),
                ('price', models.PositiveIntegerField()),
                ('phone_num', models.IntegerField(max_length=15)),
                ('floor_num', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.floor')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_verified', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_client', to='hotel_app.client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_room', to='hotel_app.room')),
            ],
        ),
    ]
