# Generated by Django 5.1.3 on 2024-11-29 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_floor', to='hotel_app.floor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
