# Generated by Django 5.1.3 on 2024-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_room_floor_num_alter_room_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Middle/Father's name"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Middle/Father's name"),
        ),
    ]
