# Generated by Django 5.1.2 on 2024-12-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='salaryhistory',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.DateField(null=True),
        ),
    ]
