# Generated by Django 5.1.2 on 2024-12-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_api', '0002_alter_contract_end_date_alter_salaryhistory_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
