# Generated by Django 5.1.2 on 2024-10-21 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_hotels', to=settings.AUTH_USER_MODEL),
        ),
    ]
