# Generated by Django 5.1.2 on 2024-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Single', 'Одноместный'), ('Double', 'Двухместный'), ('Suite', 'Люкс'), ('Family', 'Семейный')], default='Single', max_length=15),
        ),
    ]
