site_name: 'Отчёт по лабораторной работе 1'  

theme:
  name: 'material'
  palette:
    scheme: default
    primary: 'cyan' 
    accent: 'lightpurple'  
  features:
    - navigation.tabs  # Включение вкладок
    - navigation.expand  # Раскрытие подменю

nav:
  -  Главная: index.md 
  -  Задание 1: TASK1.md
  -  Задание 2: TASK2.md
  -  Задание 3: TASK3.md
  -  Задание 4: TASK4.md
  -  Задание 5: TASK5.md



