# Generated by Django 4.2.25 on 2025-11-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
    ]
