# Generated by Django 6.0.2 on 2026-02-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0002_employee_booking_cleaningassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_active",
            field=models.BooleanField(
                default=True, verbose_name="Номер в эксплуатации"
            ),
        ),
    ]
