site_name: Eva's Web Docs

nav:
  - Home: index.md
  - Labs:
      - Лабораторная работа №1:
          - "Задание 1": lab1/task_1.md
          - "Задание 2": lab1/task_2.md
          - "Задание 3": lab1/task_3.md
          - "Задание 4": lab1/task_4.md
          - "Задание 5": lab1/task_5.md
