# Generated by Django 5.1.6 on 2025-02-16 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDiscipline',
            fields=[
                ('discipline_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('discipline_name', models.CharField(max_length=128)),
                ('practice_duration', models.IntegerField()),
                ('total_duration', models.IntegerField()),
                ('attestation_type', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('type', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EducationProgram',
            fields=[
                ('programm_code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('programm_type', models.CharField(max_length=16)),
                ('duration', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('job_title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('maximum_students_amount', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('programm_code', models.ForeignKey(db_column='programm_code', on_delete=django.db.models.deletion.CASCADE, to='edu_system.educationprogram')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('class_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('classes_order_number', models.IntegerField()),
                ('type', models.CharField(max_length=16)),
                ('classroom_id', models.ForeignKey(db_column='classroom_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.classroom')),
                ('discipline_id', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.academicdiscipline')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.group')),
                ('teacher_id', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.academicdiscipline')),
                ('programm_code', models.ForeignKey(db_column='programm_code', on_delete=django.db.models.deletion.CASCADE, to='edu_system.educationprogram')),
            ],
            options={
                'unique_together': {('programm_code', 'discipline')},
            },
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='disciplines',
            field=models.ManyToManyField(related_name='programs', through='edu_system.ProgramElement', to='edu_system.academicdiscipline'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=256)),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.group')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('result', models.CharField(max_length=16)),
                ('class_id', models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.classsession')),
                ('student_id', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.student')),
            ],
        ),
        migrations.CreateModel(
            name='TeachingPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.ForeignKey(db_column='discipline_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.academicdiscipline')),
                ('teacher', models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='edu_system.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'discipline')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='disciplines',
            field=models.ManyToManyField(related_name='teachers', through='edu_system.TeachingPermit', to='edu_system.academicdiscipline'),
        ),
    ]
