# Generated by Django 5.1.3 on 2024-11-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
