# Generated by Django 5.1.3 on 2024-11-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review_app', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
