# Generated by Django 5.1.3 on 2024-11-25 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_reservation_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='floor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrival_date',
            field=models.DateField(verbose_name='Дата заселения'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(verbose_name='Дата выселения'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='room',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(100000)], verbose_name='Стоимость проживания за сутки'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Этаж'),
        ),
    ]
