# Generated by Django 5.1.2 on 2024-12-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=15, verbose_name='День недели')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=20, unique=True, verbose_name='Паспорт')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер комнаты')),
                ('room_type', models.CharField(choices=[('single', 'Одноместный'), ('double', 'Двухместный'), ('triple', 'Трехместный')], max_length=10, verbose_name='Тип комнаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за сутки')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон в комнате')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date', models.DateField(verbose_name='Дата уборки')),
                ('status', models.CharField(max_length=50, verbose_name='Статус уборки')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleanings', to='management.cleaningschedule', verbose_name='График уборки')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_confirmations', to='management.room', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала бронирования')),
                ('end_date', models.DateField(verbose_name='Дата окончания бронирования')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='management.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='management.room', verbose_name='Комната')),
            ],
        ),
        migrations.AddField(
            model_name='cleaningschedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_schedules', to='management.staff', verbose_name='Сотрудник'),
        ),
    ]
