# Generated by Django 5.1.3 on 2024-12-02 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Класс")),
            ],
        ),
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, verbose_name="Номер кабинета"),
                ),
                (
                    "is_profile",
                    models.BooleanField(
                        default=False, verbose_name="Профильный кабинет"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("m", "Мужской"), ("f", "Женский")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                ("first_name", models.CharField(max_length=120, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=120, verbose_name="Фамилия")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=120, verbose_name="Наименование предмета"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="Учебный год")),
                ("quarter", models.IntegerField(verbose_name="Четверть")),
                ("grade", models.IntegerField(verbose_name="Оценка")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.student",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.subject",
                        verbose_name="Предмет",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала обучения")),
                ("end_date", models.DateField(verbose_name="Дата окончания обучения")),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.class",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.student",
                        verbose_name="Ученик",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="school_classes",
            field=models.ManyToManyField(
                through="school_app.StudentClass",
                to="school_app.class",
                verbose_name="Классы",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="grades",
            field=models.ManyToManyField(
                through="school_app.Grade",
                to="school_app.subject",
                verbose_name="Оценки",
            ),
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=120, verbose_name="Фамилия")),
                (
                    "cabinet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school_app.classroom",
                        verbose_name="Закрепленный кабинет",
                    ),
                ),
                (
                    "leaded_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school_app.class",
                        verbose_name="Классный руководитель",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(max_length=50, verbose_name="День недели"),
                ),
                ("time", models.TimeField(verbose_name="Время занятия")),
                (
                    "class_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.class",
                        verbose_name="Класс",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="school_app.classroom",
                        verbose_name="Кабинет",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.teacher",
                        verbose_name="Учитель",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="class",
            name="lead_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leaded_classes",
                to="school_app.teacher",
                verbose_name="Классный руководитель",
            ),
        ),
        migrations.CreateModel(
            name="TeacherSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(verbose_name="Дата начала преподавания"),
                ),
                (
                    "end_date",
                    models.DateField(verbose_name="Дата окончания преподавания"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.subject",
                        verbose_name="Предмет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.teacher",
                        verbose_name="Учитель",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.ManyToManyField(
                through="school_app.TeacherSubject",
                to="school_app.subject",
                verbose_name="Предметы",
            ),
        ),
    ]
