# Generated by Django 5.1.3 on 2024-12-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="lead_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classes",
                to="school_app.teacher",
                verbose_name="Классный руководитель",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="leaded_class",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"lead_teacher__isnull": False},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_by_teacher",
                to="school_app.class",
                verbose_name="Классный руководитель",
            ),
        ),
    ]
