# Generated by Django 5.1.2 on 2024-11-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownership",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
    ]
