# Generated by Django 5.1.2 on 2024-10-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6, unique=True)),
                ('flight_type', models.CharField(choices=[('DEPARTURE', 'Departure'), ('ARRIVAL', 'Arrival')], max_length=10)),
                ('direction', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('gate', models.CharField(blank=True, max_length=4, null=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline')),
            ],
        ),
    ]
