# Generated by Django 5.1.2 on 2024-12-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_clubs_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='elevation',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
