# Generated by Django 5.1.2 on 2025-01-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_clubs_app', '0003_alter_mountain_elevation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
        migrations.AddField(
            model_name='route',
            name='duration_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
