# Generated by Django 5.1.2 on 2025-01-28 09:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_clubs_app', '0004_remove_route_duration_route_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AscentGroup',
            new_name='AscentParticipation',
        ),
    ]
