# Generated by Django 5.1.2 on 2025-01-28 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_clubs_app', '0005_rename_ascentgroup_ascentparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='clubmembership',
            name='leave_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
