# Generated by Django 5.1.2 on 2025-01-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_clubs_app', '0006_alter_clubmembership_join_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmembership',
            old_name='join_date',
            new_name='join_datetime',
        ),
        migrations.RenameField(
            model_name='clubmembership',
            old_name='leave_date',
            new_name='leave_datetime',
        ),
    ]
