# Generated by Django 5.1.2 on 2025-01-28 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpine_clubs_app', '0007_rename_join_date_clubmembership_join_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmembership',
            name='join_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
