# Generated by Django 5.1.2 on 2025-01-17 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_customer_balance_alter_order_order_date_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderInfo',
        ),
        migrations.RenameModel(
            old_name='Payment',
            new_name='PayProcess',
        ),
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
        migrations.RenameModel(
            old_name='Employee',
            new_name='Worker',
        ),
    ]
