# Generated by Django 5.1.2 on 2024-11-30 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='penalty',
        ),
        migrations.AddField(
            model_name='userhomework',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhomework',
            name='penalty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhomework',
            name='solution',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userhomework',
            name='submission_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=10, null=True),
        ),
    ]
