# Generated by Django 5.1.2 on 2024-12-03 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_alter_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='groupteacher',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board_app.group'),
        ),
    ]
