# Generated by Django 5.1.2 on 2024-12-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0008_alter_user_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudyGroup',
        ),
    ]
