# Generated by Django 5.1.2 on 2024-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0010_alter_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='group_number',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=1),
            preserve_default=False,
        ),
    ]
