# Generated by Django 5.1.2 on 2024-12-03 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0011_studygroup_group_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studygroup',
            old_name='group_number',
            new_name='group_grade',
        ),
        migrations.RenameField(
            model_name='studygroup',
            old_name='name',
            new_name='letter',
        ),
    ]
