# Generated by Django 5.1.2 on 2025-02-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0012_rename_group_number_studygroup_group_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='board_app.studygroup'),
            preserve_default=False,
        ),
    ]
