# Generated by Django 5.1.2 on 2025-02-17 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0013_homework_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhomework',
            old_name='student',
            new_name='user',
        ),
    ]
