# Generated by Django 5.1.2 on 2025-02-18 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0015_homeworksubmission_gradehomework_delete_userhomework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradehomework',
            name='user',
        ),
    ]
