# Generated by Django 5.1.3 on 2024-11-27 12:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarOwner',
            fields=[
                ('id_owner', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birthDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id_vehicle', models.AutoField(primary_key=True, serialize=False)),
                ('gosNumber', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveLicense',
            fields=[
                ('id_license', models.AutoField(primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('data_issue', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.carowner')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id_owner_car', models.AutoField(primary_key=True, serialize=False)),
                ('data_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_end', models.DateTimeField(blank=True, null=True)),
                ('id_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.carowner')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab3.vehicle')),
            ],
        ),
    ]
