# Generated by Django 5.1.3 on 2024-11-27 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivelicense',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='lab3.carowner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='lab3.carowner'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='id_vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='lab3.vehicle'),
        ),
    ]
