site_name: Лабораторные работы
nav:
 - Home: index.md
 - 1 лаба:
   - 1 задание: docs/1.md
   - 2 задание: docs/2.md
   - 3 задание: docs/3.md
   - 4 задание: docs/4.md
   - 5 задание: docs/5.md
theme:
 name: Material
