# Generated by Django 5.1.2 on 2024-11-26 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newspaper_distribution_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='newspaper_distribution_app.newspaper', verbose_name='Газета'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='post_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='newspaper_distribution_app.postoffice', verbose_name='Почтовое отделение'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='printing_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='newspaper_distribution_app.printinghouse', verbose_name='Типография'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='newspaper_distribution_app.newspaper', verbose_name='Газета'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='printing_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='newspaper_distribution_app.printinghouse', verbose_name='Типография'),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='editor',
            field=models.ForeignKey(limit_choices_to={'role': 'editor'}, on_delete=django.db.models.deletion.PROTECT, related_name='newspapers', to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
