# Generated by Django 5.1.2 on 2024-12-01 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0002_alter_owner_options_alter_owner_managers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ownership",
            old_name="car_id",
            new_name="car",
        ),
        migrations.RenameField(
            model_name="ownership",
            old_name="owner_id",
            new_name="owner",
        ),
        migrations.RemoveField(
            model_name="car",
            name="car_owner",
        ),
        migrations.RemoveField(
            model_name="driverlicense",
            name="owner_id",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="cars",
        ),
        migrations.AddField(
            model_name="car",
            name="owners",
            field=models.ManyToManyField(
                related_name="cars",
                through="project_first_app.Ownership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="driverlicense",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
