# Generated by Django 5.1.4 on 2024-12-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_customuser_passport_data_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='passport_data',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
