# Generated by Django 5.1.4 on 2024-12-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_customuser_passport_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
