# Generated by Django 5.1.4 on 2024-12-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_employee_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecase',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='insurancecase',
            name='payout_decision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
