# Generated by Django 5.1.2 on 2024-11-29 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0002_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="owner",
            name="cars",
        ),
    ]
