# Generated by Django 5.1.2 on 2024-11-30 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0003_remove_owner_cars"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license",
                to="project_first_app.owner",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership",
                to="project_first_app.car",
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownership",
                to="project_first_app.owner",
            ),
        ),
    ]
