# Generated by Django 5.1.5 on 2025-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinelink_api", "0002_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
