# Generated by Django 6.0 on 2025-12-04 14:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название гонки')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание гонки')),
            ],
            options={
                'verbose_name': 'Гонка',
                'verbose_name_plural': 'Гонки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание команды')),
                ('founded_year', models.IntegerField(blank=True, null=True, verbose_name='Год основания')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('beginner', 'Новичок'), ('intermediate', 'Промежуточный'), ('advanced', 'Продвинутый'), ('professional', 'Профессионал')], max_length=20, verbose_name='Опыт')),
                ('driver_class', models.CharField(choices=[('a', 'Класс A'), ('b', 'Класс B'), ('c', 'Класс C')], max_length=10, verbose_name='Класс')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание водителя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание автомобиля')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='races.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField(auto_now_add=True, verbose_name='Дата комментария')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('comment_type', models.CharField(choices=[('collaboration', 'Вопрос о сотрудничестве'), ('racing', 'Вопрос о гонках'), ('other', 'Иное')], max_length=20, verbose_name='Тип комментария')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='races.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Место')),
                ('time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.driver', verbose_name='Водитель')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='races.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Результат гонки',
                'verbose_name_plural': 'Результаты гонок',
                'unique_together': {('race', 'driver')},
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='races.driver', verbose_name='Водитель')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='races.race', verbose_name='Гонка')),
            ],
            options={
                'verbose_name': 'Регистрация на гонку',
                'verbose_name_plural': 'Регистрации на гонку',
                'unique_together': {('driver', 'race')},
            },
        ),
    ]
