# Generated by Django 5.1.3 on 2024-11-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="restaurant",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="tables",
            field=models.ManyToManyField(to="restaurant.table"),
        ),
    ]
