# Generated by Django 5.1.3 on 2024-11-30 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_alter_reservation_n_people_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="tables",
        ),
        migrations.AddField(
            model_name="table",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="table",
            name="table_number",
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="table",
            name="n_people",
            field=models.PositiveIntegerField(),
        ),
    ]
