# Generated by Django 5.1.2 on 2024-10-25 13:44

import django.core.validators
import django.db.models.deletion
import lr2.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.CharField(max_length=256)),
                ('name', models.TextField()),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.class')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateField()),
                ('expire_at', models.DateField()),
                ('author', models.CharField(max_length=100)),
                ('student_classes', models.ManyToManyField(to='board.class')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('grade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('graded_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField()),
                ('status', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(lr2.settings.Statuses['ISSUED']), django.core.validators.MaxValueValidator(lr2.settings.Statuses['GRADED'])])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.task')),
            ],
            options={
                'unique_together': {('task', 'student')},
            },
        ),
    ]
