# Generated by Django 4.2.16 on 2024-11-24 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО автора')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('publisher', models.CharField(max_length=50, verbose_name='Издательство')),
                ('authors', models.ManyToManyField(related_name='author_books', to='library_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=10, verbose_name='Шифр книги')),
                ('publishing_year', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(868), django.core.validators.MaxValueValidator(2023)], verbose_name='Год публикации')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='library_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('capacity', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Вместимость')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО читателя')),
                ('passport', models.CharField(max_length=20, verbose_name='Номер паспорта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('education', models.CharField(choices=[('н', 'Начальное'), ('с', 'Среднее'), ('в', 'Высшее')], max_length=1, verbose_name='Образование')),
                ('degree', models.BooleanField(default=False, verbose_name='Наличие ученой степени')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('reading_ticket', models.PositiveIntegerField(default=0, verbose_name='Номер читательского билета')),
                ('reading_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_in', to='library_app.readingroom', verbose_name='Закрепленный читальный зал')),
            ],
        ),
        migrations.CreateModel(
            name='BookTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('take_date', models.DateField(verbose_name='Дата, когда книга была взята')),
                ('return_date', models.DateField(verbose_name='Дата, когда книга была возвращена')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_takes', to='library_app.bookcopy', verbose_name='Взятая книга')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='what_is_taken', to='library_app.reader', verbose_name='Читатель')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='category_books', to='library_app.category'),
        ),
    ]
