site_name: WEB documentation
nav:
  - home: index.md
  - lab 1:
      - "task 1": lab_1/task_1.md
      - "task 2": lab_1/task_2.md
      - "task 3": lab_1/task_3.md
      - "task 4": lab_1/task_4.md
      - "task 5": lab_1/task_5.md

theme:
  name: material