site_name: 'Отчеты к лабораторным работам по веб-программированию'
nav:
  - Главная страница: index.md
  - Лабораторная работа 1:
      - Задание 1: lr_1/task1.md
      - Задание 2: lr_1/task2.md
      - Задание 3: lr_1/task3.md
      - Задание 4: lr_1/task4.md
      - Задание 5: lr_1/task5.md

theme:
  name: material
