# Generated by Django 5.1.2 on 2024-11-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racer',
            name='status',
            field=models.CharField(choices=[('platinum', 'Платиновый'), ('gold', 'Золотой'), ('silver', 'Серебряный'), ('bronze', 'Бронзовый')], default='bronze', max_length=8),
        ),
    ]
