# Generated by Django 5.1.2 on 2024-11-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_fan'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='stream_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
