# Generated by Django 5.1.2 on 2024-11-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_race_stream_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='status',
            field=models.CharField(choices=[('platinum', 'Платиновый'), ('gold', 'Золотой'), ('silver', 'Серебряный'), ('bronze', 'Бронзовый'), ('without category', 'Нет категории согласно градации FIA')], default='bronze', max_length=20),
        ),
    ]
