# Generated by Django 5.1.2 on 2024-11-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_raceparticipant_time_alter_raceparticipant_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='raceparticipant',
            old_name='time',
            new_name='lap_time',
        ),
    ]
