# Generated by Django 5.1.2 on 2024-11-03 21:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_rename_time_raceparticipant_lap_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='data_of_publication',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
