# Generated by Django 4.2.16 on 2024-11-04 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "airline",
                    models.CharField(max_length=100, verbose_name="Авиакомпания"),
                ),
                (
                    "flight_number",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Номер рейса"
                    ),
                ),
                (
                    "departure_city",
                    models.CharField(max_length=100, verbose_name="Город вылета"),
                ),
                (
                    "arrival_city",
                    models.CharField(max_length=100, verbose_name="Город прилета"),
                ),
                ("departure_time", models.DateTimeField(verbose_name="Время вылета")),
                ("arrival_time", models.DateTimeField(verbose_name="Время прилета")),
                (
                    "gate_number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Номер гейта"
                    ),
                ),
                (
                    "flight_type",
                    models.CharField(
                        choices=[("departure", "Вылет"), ("arrival", "Прилет")],
                        max_length=10,
                        verbose_name="Тип рейса",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateField(verbose_name="Дата рейса")),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="avion_app.flight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_number",
                    models.CharField(max_length=5, verbose_name="Номер места"),
                ),
                (
                    "reservation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата бронирования"
                    ),
                ),
                (
                    "flight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="avion_app.flight",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "flight", "seat_number")},
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "ticket_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Номер билета",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passengers",
                        to="avion_app.reservation",
                    ),
                ),
            ],
        ),
    ]
