site_name: Web lab 1
nav:
 - Home: index.md
 - task-1:
     - Client: task-1/Client/README.md
     - Server: task-1/Server/README.md
 - task-2:
     - Client: task-2/Client/README.md
     - Server: task-2/Server/README.md
 - task-3:
     - Client: task-3/Client/README.md
     - Server: task-3/Server/README.md
 - task-4:
     - Client: task-4/Client/README.md
     - Server: task-4/Server/README.md
 - task-5:
     - Client: task-5/Client/README.md
     - Server: task-5/Server/README.md
theme:
  name: material