site_name: "WEB-labs documentation"
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

nav:
  - Home: index.md
  - Lab №1:
    - Task 1: lab1/task_1.md
    - Task 2: lab1/task_2.md
    - Task 3: lab1/task_3.md
    - Task 4: lab1/task_4.md
    - Task 5: lab1/task_5.md
