# Generated by Django 5.1.3 on 2024-12-05 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя тренера')),
                ('last_name', models.TextField(max_length=50, verbose_name='Фамилия тренера')),
                ('middle_name', models.TextField(max_length=50, verbose_name='Отчество тренера')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Пол тренера')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения тренера')),
                ('qualification', models.TextField(max_length=100, verbose_name='Квалификация')),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Опыт работы')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('t', 'team'), ('i', 'individual')], max_length=1, verbose_name='Тип')),
                ('equipment_needed', models.BooleanField(verbose_name='Надобность оборудования')),
            ],
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя спортсмена')),
                ('last_name', models.TextField(max_length=50, verbose_name='Фамилия спортсмена')),
                ('middle_name', models.TextField(max_length=50, verbose_name='Отчество спортсмена')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Пол спортсмена')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения спортсмена')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название оборудования')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sport', verbose_name='Вид спорта')),
            ],
        ),
        migrations.CreateModel(
            name='SportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название зала')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('sport', models.ManyToManyField(to='sport_center_app.sport', verbose_name='Вид спорта')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentOfSportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('equipment', models.ManyToManyField(to='sport_center_app.equipment', verbose_name='Оборудование')),
                ('sport_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sporthall', verbose_name='Спортзал')),
            ],
        ),
        migrations.CreateModel(
            name='SportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Вместимость группы')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.coach', verbose_name='Тренер')),
                ('sport_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sporthall', verbose_name='Фамилия спортсмена')),
                ('sportsmen', models.ManyToManyField(to='sport_center_app.sportsman', verbose_name='Спортсмены')),
            ],
        ),
    ]
