# Generated by Django 5.1.3 on 2024-12-06 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsection',
            name='sport_hall',
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.TextField(max_length=10, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('sport_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sporthall', verbose_name='Зал')),
                ('sport_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sportsection', verbose_name='Секция')),
            ],
        ),
    ]
