# Generated by Django 5.1.3 on 2024-12-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center_app', '0002_remove_sportsection_sport_hall_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentofsporthall',
            name='equipment',
        ),
        migrations.AddField(
            model_name='equipmentofsporthall',
            name='equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.equipment', verbose_name='Оборудование'),
        ),
    ]
