# Generated by Django 5.1.3 on 2024-12-06 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center_app', '0003_remove_equipmentofsporthall_equipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsection',
            name='coach',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.TextField(max_length=15, verbose_name='День недели'),
        ),
        migrations.CreateModel(
            name='SportSectionCoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Принят на должность')),
                ('end', models.DateField(verbose_name='Уволен с должности')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.coach', verbose_name='Тренер')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sportsection', verbose_name='Секция')),
            ],
        ),
    ]
