# Generated by Django 5.1.3 on 2024-12-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center_app', '0004_remove_sportsection_coach_alter_schedule_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.TextField(choices=[('Monday', 'Понедельник'), ('Tuesday', 'Вторник'), ('Wednesday', 'Среда'), ('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Sunday', 'Воскресенье')], max_length=15, verbose_name='День недели'),
        ),
    ]
