# Generated by Django 5.1.3 on 2024-12-07 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center_app', '0006_alter_sportsectioncoaches_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsection',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sport', verbose_name='Вид спорта'),
        ),
    ]
