# Generated by Django 5.1.3 on 2024-12-08 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_center_app', '0007_sportsection_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsection',
            name='sport',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sport_center_app.sport', verbose_name='Вид спорта'),
            preserve_default=False,
        ),
    ]
