# Generated by Django 5.1.4 on 2024-12-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_floor_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('employee_date', models.DateField(auto_now_add=True)),
                ('fire_date', models.DateField(blank=True, null=True)),
                ('salary', models.IntegerField()),
                ('rank', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='RoomClean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.CharField(max_length=50)),
                ('clean_mark', models.IntegerField(default=5)),
                ('clean_date', models.DateField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.floor')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employee')),
            ],
        ),
    ]
