# Generated by Django 5.1.4 on 2024-12-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomclean',
            options={'verbose_name': 'Уборка этажа', 'verbose_name_plural': 'Уборка этажей'},
        ),
    ]
