# Generated by Django 5.1.4 on 2024-12-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_floor_room'),
        ('staff', '0002_alter_roomclean_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='floor',
            field=models.ManyToManyField(related_name='floor', to='rooms.floor', verbose_name='Этаж'),
        ),
    ]
