# Generated by Django 5.1.4 on 2024-12-30 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_floor_clean_date_alter_floor_fix_date_and_more'),
        ('staff', '0003_employee_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата трудоустройства'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата увольнения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=50, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport',
            field=models.CharField(max_length=50, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(verbose_name='Оклад'),
        ),
        migrations.AlterField(
            model_name='roomclean',
            name='clean_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата уборки'),
        ),
        migrations.AlterField(
            model_name='roomclean',
            name='clean_mark',
            field=models.IntegerField(default=5, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='roomclean',
            name='complaints',
            field=models.CharField(max_length=50, verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='roomclean',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='roomclean',
            name='worker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.employee', verbose_name='Уборщик'),
        ),
    ]
