# Generated by Django 5.1.4 on 2024-12-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_employee_employee_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='floor',
        ),
    ]
