# Generated by Django 4.2.20 on 2025-03-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
