# Generated by Django 5.1.2 on 2024-10-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_desk_app', '0003_class_remove_subject_teacher_subject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='homework_desk_app.class'),
        ),
    ]
