# Generated by Django 5.1.2 on 2024-11-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='owner_car',
            field=models.ManyToManyField(through='project_first_app.Possession', to='project_first_app.owner'),
        ),
    ]
