# Generated by Django 4.2.7 on 2023-11-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
    ]
