# Generated by Django 4.2.7 on 2023-11-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_alter_registration_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='recommended_for_publication',
            field=models.BooleanField(default=False),
        ),
    ]
