site_name: "dinarasaurae's webdev"
theme:
  name: 'material'
  palette:
    primary: 'orange'
    accent: 'red'

nav:
  - Home: index.md
  - LAB №1:
    - Base classes: lab1/base.md
    - Task 1: lab1/task1.md
    - Task 2: lab1/task2.md
    - Task 3: lab1/task3.md
    - Task 4: lab1/task4.md
    - Task 5: lab1/task5.md

