# Generated by Django 5.0.3 on 2024-04-02 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('floor', models.IntegerField(verbose_name='Этаж')),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год обучения')),
                ('litera', models.CharField(choices=[('A', 'А'), ('B', 'Б'), ('C', 'Ц')], max_length=1, verbose_name='Буква')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Математика'), ('Physics', 'Физика'), ('Arts', 'ИЗО'), ('Music', 'Музыка'), ('Chemisty', 'Химия'), ('Sports', 'Физическая культура'), ('Russian', 'Русский язык'), ('English', 'Английский язык'), ('Literature', 'Литература')], max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.classes', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('2', 'Неудовлетворительно'), ('3', 'Удовлетворительно'), ('4', 'Хорошо'), ('5', 'Отлично')], max_length=50, verbose_name='Оценка')),
                ('attendance', models.BooleanField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.schedules', verbose_name='Предмет в расписании')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120, verbose_name='ФИО')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.classes', verbose_name='Класс')),
                ('schedules', models.ManyToManyField(related_name='student_schedules', through='school_app.Grades', to='school_app.schedules', verbose_name='Занятия')),
            ],
        ),
        migrations.AddField(
            model_name='schedules',
            name='students',
            field=models.ManyToManyField(related_name='schedule_students', through='school_app.Grades', to='school_app.students', verbose_name='Ученики'),
        ),
        migrations.AddField(
            model_name='grades',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.students', verbose_name='Ученик'),
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=120, verbose_name='ФИО')),
                ('cabinet', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.cabinets')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teachers', verbose_name='Классный руководитель'),
        ),
        migrations.CreateModel(
            name='Teachings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(verbose_name='Стаж')),
                ('classes', models.ManyToManyField(related_name='teaching_classes', through='school_app.Schedules', to='school_app.classes', verbose_name='Классы')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.subjects', verbose_name='Предмет')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.teachers', verbose_name='Учитель')),
            ],
            options={
                'unique_together': {('teacher', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(related_name='teacher_subjects', through='school_app.Teachings', to='school_app.subjects', verbose_name='Предметы'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='teachers',
            field=models.ManyToManyField(related_name='subject_teachers', through='school_app.Teachings', to='school_app.teachers', verbose_name='Учителя'),
        ),
        migrations.AddField(
            model_name='schedules',
            name='teaching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.teachings', verbose_name='Преподавание'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachings',
            field=models.ManyToManyField(related_name='class_teachings', through='school_app.Schedules', to='school_app.teachings', verbose_name='Преподавания'),
        ),
    ]
