# Generated by Django 5.0.3 on 2024-04-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='litera',
            field=models.CharField(choices=[('A', 'А'), ('B', 'Б'), ('V', 'V'), ('G', 'Г')], max_length=1, verbose_name='Буква'),
        ),
    ]
