site_name: Лабораторная работа №1

theme:
  name: 'material'
  palette:
    primary: 'deep purple'
    accent: 'deep purple'
  font:
    text: 'Nunito'

nav:
    - Главная: index.md
    - Задание 1: task_1.md
    - Задание 2: task_2.md
    - Задание 3: task_3.md
    - Задание 4: task_4.md
    - Задание 5: task_5.md