# Generated by Django 5.1.3 on 2024-11-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels_project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="user",
            new_name="client",
        ),
    ]
