# Generated by Django 5.1.4 on 2024-12-30 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_floor_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_date', models.DateField(auto_now_add=True)),
                ('prepayment', models.IntegerField()),
                ('night_count', models.IntegerField(default=1)),
                ('guest_count', models.IntegerField(default=1)),
                ('client_preference', models.CharField(max_length=50)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
