# Generated by Django 5.1.4 on 2024-12-30 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_customuser_userprofile'),
        ('booking', '0002_booking_guest_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
