# Generated by Django 5.1.4 on 2024-12-30 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_bookings_alter_userprofile_city_and_more'),
        ('booking', '0004_alter_booking_options'),
        ('rooms', '0002_floor_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='book_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата брони'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_preference',
            field=models.CharField(max_length=50, verbose_name='Предпочтения клиента'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_count',
            field=models.IntegerField(default=1, verbose_name='Количество гостей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', verbose_name='Гость'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='night_count',
            field=models.IntegerField(default=1, verbose_name='Количество ночей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='prepayment',
            field=models.IntegerField(verbose_name='Предоплата'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Комната'),
        ),
    ]
