# Generated by Django 5.1.2 on 2024-10-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_owner_birth_date_alter_ownership_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('A', 'motorcycle'), ('B', 'car'), ('С', 'truck'), ('D', 'bus')], max_length=10),
        ),
    ]
