# Generated by Django 5.1.2 on 2024-10-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_alter_license_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('motorcycle', 'A'), ('car', 'B'), ('truck', 'С'), ('bus', 'D')], max_length=10),
        ),
    ]
