# Generated by Django 5.1.4 on 2025-01-18 15:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Данные паспорта')),
                ('city_from', models.CharField(max_length=50, verbose_name='Город проживания')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('passport_number', models.CharField(max_length=10, verbose_name='Данные паспорта')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'single'), ('d', 'double'), ('t', 'triple')], max_length=1, verbose_name='Вид номера')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Контактный номер комнаты')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(25000), django.core.validators.MaxValueValidator(100000000)], verbose_name='Стоимость проживания (в сутки)')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Этаж')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, verbose_name='День недели')),
                ('floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Этаж')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.employee', verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(verbose_name='Дата заселения')),
                ('departure_date', models.DateField(verbose_name='Дата выселения')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Администратор гостиницы')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room', verbose_name='Номер')),
            ],
        ),
    ]
