# Generated by Django 5.1.2 on 2024-10-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(through='car_owners.Ownership', to='car_owners.car'),
        ),
    ]
