# Generated by Django 5.1.4 on 2024-12-16 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('index', models.CharField(max_length=20)),
                ('editor_last_name', models.CharField(max_length=100)),
                ('editor_first_name', models.CharField(max_length=100)),
                ('editor_patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrintShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.newspaper')),
                ('printshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.printshop')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.newspaper')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.postoffice')),
                ('printshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newspaper_app.printshop')),
            ],
        ),
    ]
