# Generated by Django 5.1.4 on 2024-12-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_administration', '0002_cleaningschedule_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
    ]
