# Generated by Django 5.1.3 on 2024-12-25 00:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('passport', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('passport', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('bank_code', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('payment_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000000)])),
            ],
        ),
        migrations.CreateModel(
            name='CollectiveContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('a', 'active'), ('p', 'paused'), ('e', 'expired')], max_length=1)),
                ('type', models.CharField(choices=[('m', 'medical'), ('l', 'life-property'), ('a', 'accident'), ('g', 'mortgage')], max_length=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('a', 'active'), ('p', 'paused'), ('e', 'expired')], max_length=1)),
                ('type', models.CharField(choices=[('m', 'medical'), ('l', 'life-property'), ('a', 'accident')], max_length=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.individualclient')),
            ],
        ),
        migrations.CreateModel(
            name='InsuredEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.individualclient')),
                ('collective_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.collectivecontract')),
                ('risk_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.riskcategory')),
            ],
        ),
        migrations.CreateModel(
            name='InsuredEventEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cause', models.TextField()),
                ('decision', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuredemployee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000000)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuredeventemployee')),
            ],
        ),
        migrations.CreateModel(
            name='InsuredEventIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cause', models.TextField()),
                ('decision', models.CharField(max_length=50)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.individualcontract')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(10000000)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuredeventindividual')),
            ],
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('f', 'full-time'), ('p', 'part-time'), ('d', 'deal')], max_length=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('a', 'active'), ('p', 'paused'), ('f', 'fired'), ('e', 'expired')], max_length=1)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.agent')),
            ],
        ),
    ]
