# Generated by Django 5.1.3 on 2024-12-26 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuredemployee',
            name='collective_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insured_employees', to='insurance_app.collectivecontract'),
        ),
    ]
