# Generated by Django 5.1.3 on 2024-12-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookauthor',
            options={'ordering': ['position_on_cover'], 'verbose_name': 'Book Author', 'verbose_name_plural': 'Book Authors'},
        ),
        migrations.RemoveField(
            model_name='bookauthor',
            name='order',
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='position_on_cover',
            field=models.PositiveIntegerField(default=1, verbose_name='Position on Cover'),
            preserve_default=False,
        ),
    ]
