# Generated by Django 4.2.16 on 2024-11-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicence',
            name='car_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license', to='project_first_app.carowner'),
        ),
    ]
