# Generated by Django 4.2.16 on 2024-11-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0003_alter_driverlicence_car_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicence',
            name='car_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='project_first_app.carowner'),
        ),
    ]
