# Generated by Django 4.2.16 on 2024-11-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0005_alter_ownership_car_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(related_name='owners', through='project_first_app.Ownership', to='project_first_app.car'),
        ),
        migrations.AlterField(
            model_name='driverlicence',
            name='car_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_first_app.carowner'),
        ),
    ]
