# Generated by Django 5.1.2 on 2024-11-16 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('hotel_app', '0003_room_max_person_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='person_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='start_end_check'),
        ),
    ]
