# Generated by Django 5.1.2 on 2024-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_finished_booking_person_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='add_info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
