# Generated by Django 5.1.2 on 2024-11-18 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_checked_in'),
        ('hotel_app', '0003_room_max_person_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='rate__lte 10',
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='rate__gte 1',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rate__lte', 10)), name='rate less than 10'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 1)), name='rate more than 1'),
        ),
    ]
