# Generated by Django 5.1.3 on 2024-11-25 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_passport_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicence',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='blog.carowner'),
        ),
    ]
