# Generated by Django 5.1.3 on 2024-11-25 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_driverlicence_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_owner', to='blog.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_car', to='blog.carowner'),
        ),
    ]
