# Generated by Django 5.1.3 on 2024-11-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_ownership_car_alter_ownership_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicence',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_licence', to='blog.carowner'),
        ),
    ]
