# Generated by Django 4.2.16 on 2024-11-30 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("mb", "Minibus"),
                            ("nb", "Normal Bus"),
                            ("dd", "Double-Decker"),
                            ("eb", "Electric Bus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("passport_number", models.CharField(max_length=20, unique=True)),
                (
                    "driver_class",
                    models.CharField(
                        choices=[
                            ("MB", "Minibus driver"),
                            ("NB", "Normal Bus driver"),
                            ("DD", "Double-Decker driver"),
                            ("EB", "Electric Bus driver"),
                        ],
                        max_length=10,
                    ),
                ),
                ("experience_years", models.PositiveIntegerField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_number", models.CharField(max_length=20, unique=True)),
                ("start_point", models.CharField(max_length=100)),
                ("end_point", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("interval_minutes", models.PositiveIntegerField()),
                ("duration_minutes", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                ("shift_start", models.TimeField()),
                ("shift_end", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("0", "Active"),
                            ("1", "Completed"),
                            ("2", "Canceled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bus_management_app.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bus_management_app.driver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bus_management_app.route",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="bus_management_app.schedule",
                    ),
                ),
            ],
        ),
    ]
