# Generated by Django 5.1.7 on 2025-03-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app', '0002_remove_profile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
