# Generated by Django 5.1.3 on 2025-01-20 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512, unique=True)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField()),
                ("is_registration_opened", models.BooleanField(default=True)),
                ("free_places", models.IntegerField(default=0)),
                ("description", models.TextField()),
                ("participation_condition", models.TextField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("free_places__gte", 1)),
                        name="free_places >= 1",
                    )
                ],
            },
        ),
    ]
