# Generated by Django 5.1.3 on 2025-01-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conference",
            name="free_places >= 1",
        ),
        migrations.AddConstraint(
            model_name="conference",
            constraint=models.CheckConstraint(
                condition=models.Q(("free_places__gte", 0)), name="free_places >= 1"
            ),
        ),
    ]
