# Generated by Django 5.0 on 2023-12-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecontract',
            name='type',
            field=models.CharField(choices=[('ind', 'Индивидуальный'), ('col', 'Коллективный')], max_length=10),
        ),
    ]
