# Generated by Django 5.0 on 2023-12-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0003_alter_agent_contract'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Client',
        ),
    ]
