# Generated by Django 5.1.3 on 2024-12-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="hotel_list.reservation"
            ),
        ),
    ]
