# Generated by Django 5.1.6 on 2025-03-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0002_meal_difficulty_meal_ingredients_meal_video_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="banner",
            field=models.URLField(max_length=1024),
        ),
    ]
