# Generated by Django 5.1.4 on 2025-02-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carowner",
            name="cars",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.car"
            ),
        ),
    ]
