# Generated by Django 5.1.4 on 2025-01-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carowner',
            options={'verbose_name': 'Car Owner', 'verbose_name_plural': 'Car Owners'},
        ),
    ]
