# Generated by Django 5.1.3 on 2025-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="student_class",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="teachers",
        ),
        migrations.AlterField(
            model_name="homework",
            name="subject",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="homework",
            name="title",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("teacher", "Teacher")],
                default="student",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Class",
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
