# Generated by Django 5.1.3 on 2025-02-26 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="classroom",
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
    ]
