# Generated by Django 5.1.2 on 2024-10-29 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_booking_end_date_alter_booking_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Рейтинг должен быть минимум 1'), django.core.validators.MaxValueValidator(10, message='Рейтинг не должен превышать 10')]),
        ),
    ]
