# Generated by Django 5.1.3 on 2024-11-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('biography', models.TextField(blank=True, verbose_name='Biography')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Editor', 'Editor'), ('Other', 'Other')], max_length=20, verbose_name='Role')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order on Cover')),
                ('royalty_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Royalty Percentage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='api.author', verbose_name='Author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='api.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Book Author',
                'verbose_name_plural': 'Book Authors',
                'ordering': ['order'],
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='api.BookAuthor', to='api.author', verbose_name='Authors'),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.PositiveIntegerField(verbose_name='Edition Number')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('number_of_pages', models.PositiveIntegerField(verbose_name='Number of Pages')),
                ('has_illustrations', models.BooleanField(default=False, verbose_name='Has Illustrations')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='api.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
            },
        ),
        migrations.CreateModel(
            name='EditionEditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_responsible_editor', models.BooleanField(default=False, verbose_name='Responsible Editor')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edition_editors', to='api.edition', verbose_name='Edition')),
                ('editor', models.ForeignKey(limit_choices_to={'role': 'Editor'}, on_delete=django.db.models.deletion.CASCADE, related_name='edition_editors', to='api.employee', verbose_name='Editor')),
            ],
            options={
                'verbose_name': 'Edition Editor',
                'verbose_name_plural': 'Edition Editors',
                'unique_together': {('edition', 'editor')},
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='editors',
            field=models.ManyToManyField(limit_choices_to={'role': 'Editor'}, related_name='edited_editions', through='api.EditionEditor', to='api.employee', verbose_name='Editors'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signed', models.DateField(verbose_name='Date Signed')),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='api.edition', verbose_name='Edition')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'Manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='api.employee', verbose_name='Manager')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateField(verbose_name='Date Ordered')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.edition', verbose_name='Edition')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'unique_together': {('order', 'edition')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='api.OrderItem', to='api.edition', verbose_name='Items'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('book', 'edition_number')},
        ),
    ]
