# Generated by Django 5.2.7 on 2025-12-22 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['building', 'classroom_number'], 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-academic_year', '-semester', 'date_received'], 'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['course', 'group_name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_of_week', 'lesson_number'], 'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject_name'], 'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='hours',
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Оборудование'),
        ),
        migrations.AddField(
            model_name='grade',
            name='date_received',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(choices=[('exam', 'Экзамен'), ('test', 'Зачёт'), ('coursework', 'Курсовая работа'), ('practice', 'Практика'), ('test_module', 'Модульный контроль')], default='exam', max_length=20, verbose_name='Тип оценки'),
        ),
        migrations.AddField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to='main.teacher', verbose_name='Преподаватель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='week_type',
            field=models.CharField(choices=[('all', 'Все недели'), ('odd', 'Чётная'), ('even', 'Нечётная')], default='all', max_length=10, verbose_name='Тип недели'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours_lecture',
            field=models.PositiveSmallIntegerField(default=36, verbose_name='Лекционные часы'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours_practice',
            field=models.PositiveSmallIntegerField(default=36, verbose_name='Практические часы'),
        ),
        migrations.AddField(
            model_name='subject',
            name='hours_total',
            field=models.PositiveSmallIntegerField(default=72, verbose_name='Общее количество часов'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Код дисциплины'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Учёная степень'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(default='Преподаватель', max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='building',
            field=models.CharField(max_length=20, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID кабинета'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='Номер кабинета'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='academic_year',
            field=models.PositiveIntegerField(verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID оценки'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_value',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Осенний'), (2, 'Весенний')], verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='main.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Название группы'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='academic_year',
            field=models.PositiveIntegerField(verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='main.classroom', verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='lesson_number',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Номер пары'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID расписания'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Осенний'), (2, 'Весенний')], verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.subject', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('expelled', 'Отчислен'), ('academic', 'Академический отпуск')], default='active', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID студента'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID дисциплины'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=100, verbose_name='Название дисциплины'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='main.classroom', verbose_name='Закреплённый кабинет'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID преподавателя'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'semester', 'academic_year'), name='unique_grade_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('group', 'day_of_week', 'lesson_number', 'semester', 'academic_year'), name='unique_schedule_slot'),
        ),
    ]
