# Generated by Django 4.2.19 on 2025-03-06 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0004_alter_homeworksubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='homeworksubmission',
            options={'verbose_name': 'Сдача домашнего задания', 'verbose_name_plural': 'Сдачи домашних заданий'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_status',
            field=models.BooleanField(choices=[(True, 'Активно'), (False, 'Завершено')], default=True, verbose_name='Статус задания'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='issue_date',
            field=models.DateTimeField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='penalty_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о штрафах'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='task_text',
            field=models.TextField(verbose_name='Текст задания'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='grade',
            field=models.FloatField(blank=True, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сдачи'),
        ),
        migrations.AlterField(
            model_name='homeworksubmission',
            name='text_submission',
            field=models.TextField(verbose_name='Ответ студента'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название предмета'),
        ),
    ]
