# Generated by Django 4.2.19 on 2025-03-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_alter_homeworksubmission_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Задание сдано'),
        ),
    ]
