# Generated by Django 4.2.19 on 2025-03-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_homeworksubmission_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworksubmission',
            name='is_submitted',
        ),
    ]
