# Generated by Django 5.1.2 on 2024-11-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab1_Petukhov', '0003_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='payment_conditions',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_conditions',
            field=models.TextField(blank=True),
        ),
    ]
