# Generated by Django 5.1.2 on 2024-11-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab1_Petukhov', '0007_reservation_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(default='rus', max_length=100),
            preserve_default=False,
        ),
    ]
