site_name: Документация лабораторных работ WEB Мельник Софья
theme:
  name: 'material'
nav:
  - Главная: index.md
  - Лабораторная работа 1:
      - task1.md
      - task2.md
      - task3.md
      - task4.md
      - task5.md
  - Лабораторная работа 2:
      - leetcodes_lr2.md
      - lab2_urls.md
      - lab2_models.md
      - lab2_views.md
  - Лабораторная работа 3:
      - leetcodes_lr3.md
      - task3_1.md
      - lab3.md
  - Лабораторная работа 4:
      - leetcodes_lr4.md
      - lab4.md