# Generated by Django 5.1.3 on 2024-12-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airline",
            old_name="address",
            new_name="country",
        ),
        migrations.AddField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Boarding", "Boarding"),
                    ("Boarding Complete", "Boarding Complete"),
                    ("In Air", "In Air"),
                    ("Landing", "Landing"),
                    ("Delayed", "Delayed"),
                    ("Canceled", "Canceled"),
                ],
                default="Scheduled",
                max_length=50,
            ),
        ),
    ]
