# Generated by Django 5.1.3 on 2024-12-03 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0002_rename_address_airline_country_flight_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="plane",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flights",
                to="airline_app.plane",
            ),
        ),
    ]
