# Generated by Django 5.1.3 on 2024-12-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0003_alter_flight_plane"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaneModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("seats_capacity", models.IntegerField()),
                ("speed", models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name="plane",
            name="seats_capacity",
        ),
        migrations.RemoveField(
            model_name="plane",
            name="speed",
        ),
        migrations.AlterField(
            model_name="plane",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planes",
                to="airline_app.planemodel",
            ),
        ),
    ]
