# Generated by Django 5.1.3 on 2024-12-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0004_planemodel_remove_plane_seats_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="number",
            field=models.CharField(default="", max_length=10),
        ),
    ]
