# Generated by Django 5.1.3 on 2024-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0005_route_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
