# Generated by Django 5.1.3 on 2024-12-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0006_alter_route_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crew",
            name="captain",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="captain_of",
                to="airline_app.crewmember",
            ),
        ),
        migrations.AlterField(
            model_name="crew",
            name="co_pilot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="co_pilot_of",
                to="airline_app.crewmember",
            ),
        ),
        migrations.AlterField(
            model_name="crew",
            name="navigator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="navigator_of",
                to="airline_app.crewmember",
            ),
        ),
    ]
