# Generated by Django 5.1.3 on 2024-12-05 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0007_alter_crew_captain_alter_crew_co_pilot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="arrival_datetime",
        ),
        migrations.RemoveField(
            model_name="flight",
            name="departure_datetime",
        ),
        migrations.RemoveField(
            model_name="route",
            name="stops",
        ),
        migrations.RemoveField(
            model_name="transitstop",
            name="arrival_datetime",
        ),
        migrations.RemoveField(
            model_name="transitstop",
            name="departure_datetime",
        ),
        migrations.RemoveField(
            model_name="transitstop",
            name="flight",
        ),
        migrations.AddField(
            model_name="flight",
            name="arrival_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="flight",
            name="departure_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="arrival_day",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="arrival_time",
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="route",
            name="departure_time",
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="transitstop",
            name="arrival_day",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="transitstop",
            name="arrival_time",
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="transitstop",
            name="departure_day",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="transitstop",
            name="departure_time",
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="transitstop",
            name="route",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transit_stops",
                to="airline_app.route",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="flights",
                to="airline_app.route",
            ),
        ),
    ]
