# Generated by Django 5.1.3 on 2024-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0008_remove_flight_arrival_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="regularity",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
