# Generated by Django 5.1.3 on 2024-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0009_route_regularity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="status",
            field=models.CharField(
                choices=[
                    ("Scheduled", "Scheduled"),
                    ("Boarding", "Boarding"),
                    ("Boarding Complete", "Boarding Complete"),
                    ("In Air", "In Air"),
                    ("Landing", "Landing"),
                    ("Complete", "Complete"),
                    ("Delayed", "Delayed"),
                    ("Canceled", "Canceled"),
                ],
                default="Scheduled",
                max_length=50,
            ),
        ),
    ]
