# Generated by Django 5.1.3 on 2024-12-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airline_app", "0010_alter_flight_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="arrival_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="departure_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="airline_app.route",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="arrival_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="route",
            name="arrival_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="departure_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="route",
            name="regularity",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="transitstop",
            name="arrival_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transitstop",
            name="arrival_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="transitstop",
            name="departure_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transitstop",
            name="departure_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="transitstop",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transit_stops",
                to="airline_app.route",
            ),
        ),
    ]
