# Generated by Django 5.1.4 on 2024-12-07 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField()),
                ('anamnesis', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
                ('diagnosis_kind', models.CharField(choices=[('circulatory diseases', 'Болезни системы кровообращения'), ('respiratory diseases', 'Болезни органов дыхания'), ('digestive diseases', 'Болезни органов пищеварения'), ('musculoskeletal diseases', 'Заболевания опорно-двигательного аппарата'), ('urinary diseases', 'Болезни мочевыводящих путей'), ('blood diseases', 'Заболевания крови'), ('endocrine diseases', 'Заболевания эндокринной системы')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('specialization', models.CharField(max_length=100)),
                ('education', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Муж'), ('Female', 'Жен')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField()),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Муж'), ('Female', 'Жен')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_type', models.CharField(choices=[('underlying disease', 'Основное заболевание'), ('complication of the underlying', 'Осложнение основного заболевания'), ('concomitant', 'Сопутствующее заболевание')], max_length=50)),
                ('diagnosis_status', models.CharField(choices=[('Confirmed', 'Подтвержден'), ('Tentative', 'Предварительный'), ('Pending', 'В ожидании')], max_length=15)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.appointment')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.diagnosis')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='medical_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.medicalcard'),
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.patient'),
        ),
        migrations.CreateModel(
            name='EmploymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_number', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.position')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Assigned', 'Назначена'), ('Provided', 'Проведена')], max_length=10)),
                ('date_of_service', models.DateField()),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.appointment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForProvidedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('Paid', 'Оплачено'), ('Unpaid', 'Не оплачено'), ('Partial', 'Частично оплачено')], max_length=10)),
                ('payment_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('provided_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.providedservice')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(unique=True)),
                ('internal_phone', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_working_day', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.room')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSpecialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.specialization')),
            ],
        ),
    ]
