# Generated by Django 5.1.4 on 2024-12-07 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdiagnosis',
            name='diagnosis_status',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='diagnosis_kind',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='room',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_name',
        ),
        migrations.AddField(
            model_name='appointmentdiagnosis',
            name='status',
            field=models.CharField(choices=[('Confirmed', 'Confirmed'), ('Tentative', 'Tentative'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='kind',
            field=models.CharField(choices=[('circulatory diseases', 'Circulatory Diseases'), ('respiratory diseases', 'Respiratory Diseases'), ('digestive diseases', 'Digestive Diseases'), ('diseases of the musculoskeletal system', 'Musculoskeletal Diseases'), ('diseases of the urinary system', 'Urinary Diseases'), ('blood diseases', 'Blood Diseases'), ('diseases of the endocrine system', 'Endocrine Diseases')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='specializations',
            field=models.ManyToManyField(related_name='employees', through='clinic_app.EmployeeSpecialization', to='clinic_app.specialization'),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AddField(
            model_name='service',
            name='service',
            field=models.CharField(default='Default description', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_app.employee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medical_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_app.medicalcard'),
        ),
        migrations.AlterField(
            model_name='appointmentdiagnosis',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinic_app.appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentdiagnosis',
            name='illness_type',
            field=models.CharField(choices=[('underlying disease', 'Underlying Disease'), ('complication of the underlying', 'Complication'), ('concomitant', 'Concomitant Disease')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='clinic_app.employee'),
        ),
        migrations.AlterField(
            model_name='employmentperiod',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_periods', to='clinic_app.employee'),
        ),
        migrations.AlterField(
            model_name='employmentperiod',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_periods', to='clinic_app.position'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_card', to='clinic_app.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentforprovidedservice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentforprovidedservice',
            name='provided_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinic_app.providedservice'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to='clinic_app.appointment'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_services', to='clinic_app.service'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Provided', 'Provided')], max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='clinic_app.service'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='employeespecialization',
            table='clinic_app_employeespecialization',
        ),
    ]
