# Generated by Django 5.1.4 on 2024-12-07 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_remove_appointmentdiagnosis_diagnosis_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdiagnosis',
            name='status',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='specializations',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service',
        ),
        migrations.AddField(
            model_name='appointmentdiagnosis',
            name='diagnosis_status',
            field=models.CharField(choices=[('Confirmed', 'Подтвержден'), ('Tentative', 'Предварительный'), ('Pending', 'В ожидании')], default='Pending', max_length=15),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosis_kind',
            field=models.CharField(choices=[('circulatory diseases', 'Болезни системы кровообращения'), ('respiratory diseases', 'Болезни органов дыхания'), ('digestive diseases', 'Болезни органов пищеварения'), ('musculoskeletal diseases', 'Заболевания опорно-двигательного аппарата'), ('urinary diseases', 'Болезни мочевыводящих путей'), ('blood diseases', 'Заболевания крови'), ('endocrine diseases', 'Заболевания эндокринной системы')], default='respiratory', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(default='Default service name', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='medical_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.medicalcard'),
        ),
        migrations.AlterField(
            model_name='appointmentdiagnosis',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.appointment'),
        ),
        migrations.AlterField(
            model_name='appointmentdiagnosis',
            name='illness_type',
            field=models.CharField(choices=[('underlying disease', 'Основное заболевание'), ('complication of the underlying', 'Осложнение основного заболевания'), ('concomitant', 'Сопутствующее заболевание')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Муж'), ('Female', 'Жен')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee'),
        ),
        migrations.AlterField(
            model_name='employmentperiod',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee'),
        ),
        migrations.AlterField(
            model_name='employmentperiod',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.position'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.patient'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Муж'), ('Female', 'Жен')], max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentforprovidedservice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Оплачено'), ('Unpaid', 'Не оплачено'), ('Partial', 'Частично оплачено')], max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentforprovidedservice',
            name='provided_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.providedservice'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.appointment'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.service'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Назначена'), ('Provided', 'Проведена')], max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.service'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='employeespecialization',
            table=None,
        ),
    ]
