# Generated by Django 5.1.4 on 2024-12-07 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_remove_appointmentdiagnosis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(default='Default description'),
        ),
        migrations.AlterField(
            model_name='appointmentdiagnosis',
            name='diagnosis_status',
            field=models.CharField(choices=[('Confirmed', 'Подтвержден'), ('Tentative', 'Предварительный'), ('Pending', 'В ожидании')], max_length=10),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_kind',
            field=models.CharField(choices=[('circulatory diseases', 'Circulatory Diseases'), ('respiratory diseases', 'Respiratory Diseases'), ('digestive diseases', 'Digestive Diseases'), ('musculoskeletal diseases', 'Diseases of Musculoskeletal System'), ('urinary diseases', 'Urinary System Diseases'), ('blood diseases', 'Blood Diseases'), ('endocrine diseases', 'Endocrine System Diseases')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_app.employee'),
        ),
    ]
