# Generated by Django 5.1.4 on 2024-12-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_service_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Муж'), ('Female', 'Жен')], max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
