# Generated by Django 5.1.4 on 2024-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_alter_patient_gender_alter_patient_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_kind',
            field=models.CharField(choices=[('circulatory diseases', 'Болезни системы кровообращения'), ('respiratory diseases', 'Болезни органов дыхания'), ('digestive diseases', 'Болезни органов пищеварения'), ('musculoskeletal diseases', 'Заболевания опорно-двигательного аппарата'), ('urinary diseases', 'Болезни мочевыводящих путей'), ('blood diseases', 'Заболевания крови'), ('endocrine diseases', 'Заболевания эндокринной системы')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Муж'), ('Female', 'Жен')], max_length=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='internal_phone',
            field=models.CharField(max_length=11),
        ),
    ]
