# Generated by Django 5.1.4 on 2024-12-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_alter_diagnosis_diagnosis_kind_alter_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdiagnosis',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='clinic_app.appointment'),
        ),
    ]
