# Generated by Django 5.1.4 on 2024-12-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0007_alter_appointmentdiagnosis_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcard',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic_app.diagnosis'),
        ),
    ]
