# Generated by Django 5.1.4 on 2024-12-08 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0008_medicalcard_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_app.patient'),
            preserve_default=False,
        ),
    ]
