# Generated by Django 5.1.3 on 2024-11-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=70, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=70, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Отчество"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="Дата найма")),
                (
                    "dismissal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата увольнения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Работник гостиницы",
                "verbose_name_plural": "Работники гостиницы",
                "db_table": "employee",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.SmallIntegerField(unique=True, verbose_name="Номер этажа"),
                ),
            ],
            options={
                "verbose_name": "Этаж",
                "verbose_name_plural": "Этажи",
                "db_table": "floor",
            },
        ),
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=70, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=70, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "passport",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        verbose_name="Серия и номер паспорта",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="Город")),
            ],
            options={
                "verbose_name": "Гость",
                "verbose_name_plural": "Гости",
                "db_table": "guest",
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beds",
                    models.PositiveIntegerField(verbose_name="Количество кроватей"),
                ),
                (
                    "price_per_day",
                    models.PositiveIntegerField(verbose_name="Цена за день"),
                ),
            ],
            options={
                "verbose_name": "Тип гостиничного номера",
                "verbose_name_plural": "Типы гостиничых номеров",
                "db_table": "room_type",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_in_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата заселения"),
                ),
                ("check_out_date", models.DateField(verbose_name="Дата выселения")),
                (
                    "guest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.guest",
                        verbose_name="Гость",
                    ),
                ),
            ],
            options={
                "db_table": "booking",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Номер на двери"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotel_app.floor",
                        verbose_name="Этаж",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotel_app.roomtype",
                        verbose_name="Тип номера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Гостиничный номер",
                "verbose_name_plural": "Гостиничные номера",
                "db_table": "room",
            },
        ),
        migrations.AddField(
            model_name="guest",
            name="rooms",
            field=models.ManyToManyField(
                related_name="guests", through="hotel_app.Booking", to="hotel_app.room"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_app.room",
                verbose_name="Гостиничный номер",
            ),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_day",
                    models.CharField(
                        choices=[
                            ("пн", "понедельник"),
                            ("вт", "вторник"),
                            ("ср", "среда"),
                            ("чт", "четверг"),
                            ("пт", "пятница"),
                            ("сб", "суббота"),
                            ("вс", "воскресенье"),
                        ],
                        max_length=2,
                        verbose_name="День недели",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="hotel_app.employee",
                        verbose_name="Работник",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_app.floor",
                        verbose_name="Этаж",
                    ),
                ),
            ],
            options={
                "db_table": "schedule",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="floors",
            field=models.ManyToManyField(
                related_name="employees",
                through="hotel_app.Schedule",
                to="hotel_app.floor",
            ),
        ),
    ]
