# Generated by Django 5.1.3 on 2024-11-15 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0002_alter_booking_guest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booking",
                to="hotel_app.room",
                verbose_name="Гостиничный номер",
            ),
        ),
    ]
