# Generated by Django 5.1.2 on 2024-10-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_carowner_options_alter_carowner_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='address',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carowner',
            name='nationality',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carowner',
            name='passport_data',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
