site_name: WEB 2.2 Пеньков Георгий
theme:
    name: dracula
nav:
  - Home: index.md
  - "Лабораторная 1":
      - "Задание 1": lab1/task1.md
      - "Задание 2": lab1/task2.md
      - "Задание 3": lab1/task3.md
      - "Задание 4": lab1/task4.md
      - "Задание 5": lab1/task5.md