site_name: WEB docs
nav:
  - Home: index.md
  - Lab 1:
      - "Task 1": Lr1/task1.md
      - "Task 2": Lr1/task2.md
      - "Task 3": Lr1/task3.md
      - "Task 4": Lr1/task4.md
      - "Task 5": Lr1/task5.md
  - Lab 2:
      - "Task": Lr2/lr2.md
  - Lab 3:
      - "Practical work": Lr3/pr3.1.md
      - "Laboratory work": Lr3/lr3_api.md

theme:
  name: material