# Generated by Django 5.1.3 on 2024-11-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_library_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_discarded",
            field=models.BooleanField(default=False),
        ),
    ]
