# Generated by Django 5.1.3 on 2024-11-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_library_app", "0003_booktransaction_returned"),
    ]

    operations = [
        migrations.AddField(
            model_name="reader",
            name="re_registered",
            field=models.BooleanField(default=False),
        ),
    ]
