# Generated by Django 5.1.2 on 2024-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragency',
            name='country',
            field=models.CharField(default='Россия', max_length=100),
            preserve_default=False,
        ),
    ]
