# Generated by Django 5.1.2 on 2024-11-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_touragency_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='participants_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='return_policy',
            field=models.CharField(choices=[('refundable', 'С возможностью возврата'), ('non_refundable', 'Без возможности возврата')], default='refundable', max_length=15),
        ),
    ]
