# Generated by Django 5.1.2 on 2024-11-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_reservation_participants_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(default='Австралия', max_length=100),
            preserve_default=False,
        ),
    ]
