# Generated by Django 5.1.2 on 2024-11-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
