site_name: 'Отчёт по проекту'
theme:
  name: 'material'
  palette:
    scheme: default
    primary: pink
    accent: pink

nav:
  - Главная: index.md
  - Глава 1: TASK1.md
  - Глава 2: TASK2.md
  - Глава 3: TASK3.md
  - Глава 4: TASK4.md
  - Глава 5: TASK5.md

extra_css:
  - css/extra.css
