# Generated by Django 5.1.3 on 2024-11-25 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice31', '0002_alter_carowner_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_owner', to='practice31.owner'),
        ),
    ]
