site_name: WEB-programming
nav:
    - Home: index.md
    - 1 lab:
      - Task 1: lr1/1.md
      - Task 2: lr1/2.md
      - Task 3: lr1/3.md
      - Task 4: lr1/4.md
      - Task 5: lr1/5.md
theme:
    name: readthedocs