# Generated by Django 5.1.6 on 2025-02-14 23:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название конференции')),
                ('topics', models.TextField(help_text='Перечислите тематики конференции через запятую', verbose_name='Тематики')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('description', models.TextField(verbose_name='Описание конференции')),
                ('location_description', models.TextField(verbose_name='Описание места проведения')),
                ('participation_conditions', models.TextField(verbose_name='Условия участия')),
                ('recommended_for_publication', models.BooleanField(blank=True, help_text='Администратор может указать результат выступления', null=True, verbose_name='Рекомендовано к публикации')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('presentation_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название выступления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conference_app.conference')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='conference_app.conference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
