# Generated by Django 5.1.2 on 2024-11-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
