# Generated by Django 5.1.2 on 2024-11-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_alter_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_person_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
