# Generated by Django 5.1.5 on 2025-01-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinelink_api", "0004_alter_activity_options_alter_friend_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
