login:
	curl -X POST -d "username=${USERNAME}&password=${PASSWORD}&email=${EMAIL}&re_password=${REPASSWORD}" http://localhost:8000/auth/users/

get-token:
	curl -X POST -d "username=${USERNAME}&password=${PASSWORD}" http://localhost:8000/auth/token/login
