"""empty message

Revision ID: c1cf70dec3d7
Revises: 
Create Date: 2024-11-26 22:25:05.557223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1cf70dec3d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('people_capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_number', sa.String(length=32), nullable=False),
    sa.Column('bus_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_date', sa.DateTime(), nullable=False),
    sa.Column('to_date', sa.DateTime(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_experience_over_months', sa.Integer(), nullable=False),
    sa.Column('driver_class_id', sa.Integer(), nullable=False),
    sa.Column('salary_rub', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('monday', sa.String(length=11), nullable=True),
    sa.Column('tuesday', sa.String(length=11), nullable=True),
    sa.Column('wednesday', sa.String(length=11), nullable=True),
    sa.Column('thursday', sa.String(length=11), nullable=True),
    sa.Column('friday', sa.String(length=11), nullable=True),
    sa.Column('saturday', sa.String(length=11), nullable=True),
    sa.Column('sunday', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=32), nullable=False),
    sa.Column('passport_info', sa.String(length=10), nullable=False),
    sa.Column('driver_class_id', sa.Integer(), nullable=False),
    sa.Column('work_experience_months', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('start_point_name', sa.String(length=32), nullable=False),
    sa.Column('end_point_name', sa.String(length=32), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('drivers')
    op.drop_table('driver_work_schedules')
    op.drop_table('driver_salaries')
    op.drop_table('driver_classes')
    op.drop_table('driver_assignments')
    op.drop_table('buses')
    op.drop_table('bus_types')
    # ### end Alembic commands ###
