# Generated by Django 5.1.2 on 2024-11-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Standard Single', 'Standard Single'), ('Standard Double', 'Standard Double'), ('Standard Twin', 'Standard Twin'), ('Quadruple Room', 'Quadruple Room'), ('Presidential Suit', 'Presidential Suit')], default='SS', max_length=17),
        ),
    ]
