# Generated by Django 5.1.2 on 2024-11-03 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
    ]
