# Generated by Django 5.1.2 on 2024-11-04 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0002_remove_commentary_dislikes_remove_commentary_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
