# Generated by Django 5.1.2 on 2024-11-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0004_participant_email_alter_participant_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceperformance',
            name='date_of_finish',
        ),
        migrations.RemoveField(
            model_name='conferenceperformance',
            name='date_of_start',
        ),
    ]
