# Generated by Django 5.1.2 on 2024-11-06 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('science', '0005_remove_conferenceperformance_date_of_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='creator',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='science.participant'),
            preserve_default=False,
        ),
    ]
