site_name: Web Programming Docs
nav:
  - Home: index.md
  - Lr1:
      - task1: Lr1/task1.md
      - task2: Lr1/task2.md
      - task3: Lr1/task3.md
      - task4: Lr1/task4.md
      - task5: Lr1/task5.md

theme:
  name: material