# Generated by Django 4.2.20 on 2025-03-09 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_alter_user_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
