# Generated by Django 5.1.2 on 2024-11-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_alter_charactersskill_bonus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='abribute',
            new_name='attribute',
        ),
        migrations.AlterField(
            model_name='character',
            name='attributes',
            field=models.ManyToManyField(blank=True, through='characters.CharactersAttribute', to='characters.attribute'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(blank=True, through='characters.CharactersSkill', to='characters.skill'),
        ),
    ]
