# Generated by Django 5.1.2 on 2024-11-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0002_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
