# Generated by Django 5.1.2 on 2024-10-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_review_user_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='race',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='user',
        ),
        migrations.AddField(
            model_name='bookings',
            name='ticket',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='app.ticket'),
            preserve_default=False,
        ),
    ]
