# Generated by Django 6.0.2 on 2026-02-15 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelsales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="adults",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="Взрослые"),
        ),
        migrations.AddField(
            model_name="booking",
            name="children",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Дети"),
        ),
    ]
