# Generated by Django 6.0.2 on 2026-02-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelsales", "0002_booking_adults_booking_children"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(blank=True, null=True, verbose_name="Заезд"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(blank=True, null=True, verbose_name="Выезд"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=12, null=True
            ),
        ),
    ]
