# Generated by Django 6.0.2 on 2026-02-16 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotelsales", "0003_alter_booking_check_in_alter_booking_check_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="hotels/", verbose_name="Фото отеля"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Общая стоимость",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
    ]
