# Generated by Django 5.1.3 on 2024-11-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelCompany', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
