# Generated by Django 5.0 on 2023-12-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0004_rename_person_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occured', models.DateField()),
                ('reason', models.CharField(max_length=200)),
                ('decision', models.BooleanField()),
                ('payout_amount', models.IntegerField(null=True)),
                ('insurance_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurancecontract')),
            ],
        ),
    ]
