# Generated by Django 5.1.3 on 2024-11-27 14:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alpinist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ascending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('fact_start_date', models.DateField(blank=True, null=True)),
                ('fact_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=150)),
                ('e_mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9000)])),
                ('country', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AscendingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_result', models.CharField(choices=[('s', 'success'), ('f', 'failure'), ('o', 'other')], max_length=1)),
                ('description_of_result', models.TextField()),
                ('ascending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinist_club_app.ascending')),
            ],
        ),
        migrations.CreateModel(
            name='AlpinistInGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('s', 'success'), ('f', 'failure'), ('e', 'emergency'), ('o', 'other')], max_length=1)),
                ('alpinist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinist_club_app.alpinist')),
                ('ascendingGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinist_club_app.ascendinggroup')),
            ],
        ),
        migrations.AddField(
            model_name='alpinist',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinist_club_app.club'),
        ),
        migrations.AddField(
            model_name='ascending',
            name='mountain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alpinist_club_app.mountain'),
        ),
    ]
