# Generated by Django 5.1.3 on 2024-11-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinist_club_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alpinistingroup',
            name='emergency_situations',
            field=models.CharField(choices=[('t', 'trauma'), ('l', 'lethal'), ('m', 'missing')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='alpinistingroup',
            name='result',
            field=models.CharField(choices=[('s', 'success'), ('f', 'failure'), ('e', 'emergency'), ('o', 'other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ascendinggroup',
            name='description_of_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ascendinggroup',
            name='group_result',
            field=models.CharField(blank=True, choices=[('s', 'success'), ('f', 'failure'), ('o', 'other')], max_length=1, null=True),
        ),
    ]
