# Generated by Django 5.1.3 on 2024-11-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alpinist_club_app', '0002_alpinistingroup_emergency_situations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alpinistingroup',
            old_name='ascendingGroup',
            new_name='ascending_group_id',
        ),
    ]
