# Generated by Django 5.1.3 on 2024-11-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alpinist_club_app', '0003_rename_ascendinggroup_alpinistingroup_ascending_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascendinggroup',
            name='members',
            field=models.ManyToManyField(through='alpinist_club_app.AlpinistInGroup', to='alpinist_club_app.alpinist'),
        ),
    ]
