# Generated by Django 5.1.2 on 2024-10-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_hotel_app', '0002_rename_room_id_reservation_room_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reservation_id',
            new_name='reservation',
        ),
    ]
