site_name: Laboratory work 1
nav:
  - Task_1: task-1.md
  - Task-2: task-2.md
  - Task-3: task-3.md
  - Task-4: task-4.md
  - Task-5: task-5.md
  - Conclusion: conclusion.md

extra_css:
  - css/custom.css
