# Generated by Django 5.1.2 on 2024-11-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_hotelbaseaccount_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbaseaccount',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='hotelbaseaccount',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='hotelbaseaccount',
            name='user_permissions',
        ),
    ]
