# Generated by Django 5.1.2 on 2024-12-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AutorepairShop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
