# Generated by Django 5.0.3 on 2024-03-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_rename_car_id_car_number_car_car_owner_owner_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='owner',
            name='passport',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
