# Generated by Django 5.1.2 on 2024-10-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='make',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='state_number',
            new_name='plate_number',
        ),
    ]
