# Generated by Django 5.1.3 on 2024-12-29 18:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lr3app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='route',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='experience_years',
            new_name='work_experience',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='end_time',
            new_name='operation_end_time',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_time',
            new_name='operation_start_time',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='route',
            name='interval_minutes',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_number',
        ),
        migrations.AddField(
            model_name='bus',
            name='in_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='interval',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='registration_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bustype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_class',
            field=models.CharField(choices=[('A', 'Class A'), ('B', 'Class B'), ('C', 'Class C')], max_length=1),
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Worked', 'Worked'), ('Absent', 'Absent'), ('Sick', 'Sick'), ('Breakdown', 'Breakdown'), ('No Driver', 'No Driver'), ('No Bus', 'No Bus')], default='Worked', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr3app.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr3app.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lr3app.route')),
            ],
            options={
                'unique_together': {('driver', 'date', 'shift_start_time', 'shift_end_time')},
            },
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
