# Generated by Django 3.2.19 on 2024-11-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='registered_at',
        ),
        migrations.AddField(
            model_name='registration',
            name='topic',
            field=models.CharField(default='No topic provided', max_length=255, verbose_name='Presentation Topic'),
        ),
    ]
