# Generated by Django 5.1.3 on 2024-11-29 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_build', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type_diet', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Habited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Valliere_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(choices=[('f', 'самка'), ('m', 'самец')], max_length=1)),
                ('name', models.CharField(max_length=100)),
                ('birtday', models.DateField()),
                ('animal_type', models.CharField(max_length=100)),
                ('is_buy', models.BooleanField()),
                ('is_rented', models.CharField(blank=True, choices=[('in', 'Взят'), ('out', 'Сдан')], max_length=3, null=True)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zoo_app.diet')),
                ('habited', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo_app.habited')),
            ],
        ),
        migrations.CreateModel(
            name='NoteReptile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normal_temperature', models.IntegerField()),
                ('begin_wintering', models.DateField()),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='NoteBird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wintering', models.BooleanField()),
                ('country_wintering', models.CharField(blank=True, max_length=100, null=True)),
                ('start_wintering', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_wintering', models.CharField(blank=True, max_length=100, null=True)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=100)),
                ('date_buy', models.DateField()),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.pet')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='products',
            field=models.ManyToManyField(to='zoo_app.product'),
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoo', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('start_rent', models.DateField()),
                ('finish_rent', models.DateField()),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Valliere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_commun', models.BooleanField()),
                ('is_isolated', models.BooleanField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo_app.building')),
                ('params', models.ManyToManyField(to='zoo_app.valliere_parameter')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='valliere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zoo_app.valliere'),
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('father_name', models.CharField(blank=True, max_length=40, null=True)),
                ('birtday', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?\\d{0,15}$')])),
                ('animals', models.ManyToManyField(to='zoo_app.pet')),
            ],
        ),
    ]
