# Generated by Django 5.1.3 on 2024-11-29 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type_build',
            field=models.CharField(choices=[('s', 'летнее'), ('w', 'зимнее')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notebird',
            name='finish_wintering',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notebird',
            name='start_wintering',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_employer', models.CharField(choices=[('v', 'ветеринар'), ('z', 'смотритель зоопарка')], max_length=1)),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('father_name', models.CharField(blank=True, max_length=40, null=True)),
                ('birtday', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона.', regex='^\\+?\\d{0,15}$')])),
                ('animals', models.ManyToManyField(to='zoo_app.pet')),
            ],
        ),
        migrations.DeleteModel(
            name='Veterinarian',
        ),
    ]
