# Generated by Django 5.1.3 on 2024-11-29 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0002_alter_building_type_build_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='animal_type',
            new_name='depart',
        ),
    ]
