# Generated by Django 5.1.3 on 2024-11-29 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0003_rename_animal_type_building_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_pet', to='zoo_app.pet'),
        ),
    ]
