# Generated by Django 5.1.3 on 2024-11-29 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0004_alter_buy_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_pet', to='zoo_app.pet'),
        ),
    ]
