# Generated by Django 5.1.3 on 2024-11-29 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0005_alter_rent_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebird',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_bird_pet', to='zoo_app.pet'),
        ),
        migrations.AlterField(
            model_name='notereptile',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='note_reptile_pet', to='zoo_app.pet'),
        ),
    ]
