# Generated by Django 5.1.3 on 2024-11-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0006_alter_notebird_pet_alter_notereptile_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='animals',
            field=models.ManyToManyField(related_name='employers_pet', to='zoo_app.pet'),
        ),
    ]
