# Generated by Django 5.1.3 on 2024-11-29 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0007_alter_employer_animals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='diet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='zoo_app.diet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='habited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets', to='zoo_app.habited'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='valliere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='zoo_app.valliere'),
        ),
    ]
