# Generated by Django 5.1.3 on 2024-11-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0008_alter_pet_diet_alter_pet_habited_alter_pet_valliere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valliere',
            name='params',
            field=models.ManyToManyField(blank=True, to='zoo_app.valliere_parameter'),
        ),
    ]
