# Generated by Django 5.1.3 on 2024-11-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo_app', '0009_alter_valliere_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebird',
            name='finish_wintering',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notebird',
            name='start_wintering',
            field=models.DateField(blank=True, null=True),
        ),
    ]
