site_name: web_labs
nav:
  - Home: index.md
  - Lab 1:
      - "Task 1": lab1/task1.md
      - "Task 2": lab1/task2.md
      - "Task 3": lab1/task3.md
      - "Task 4": lab1/task4.md
      - "Task 5": lab1/task5.md
theme:
  name: null
  custom_dir: 'cinder'