# Generated by Django 5.1.2 on 2024-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0007_alter_owner_groups_alter_owner_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
