# Generated by Django 5.1.2 on 2024-10-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('project_first_app', '0008_owner_birthday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='owner_set', to='auth.permission', verbose_name='owner permissions'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='owner_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
