version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: default_user
      POSTGRES_PASSWORD: default
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://default_user:default@db:5432/task_manager

  parser:
    build: .
    restart: always
    command: ["uvicorn", "parser_app:app", "--host", "0.0.0.0", "--port", "8001"]
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://default_user:default@db:5432/task_manager

  celery:
    build: .
    restart: always
    command: ["celery", "-A", "celery_config.app", "worker", "--loglevel=info"]
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgresql://default_user:default@db:5432/task_manager

volumes:
  db_data: