# Generated by Django 5.2.8 on 2025-12-03 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.PositiveIntegerField(verbose_name='Номер кабинета')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('course', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Курс')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специальность')),
                ('created_year', models.IntegerField(verbose_name='Год создания')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('enrollment_date', models.DateField(verbose_name='Дата поступления')),
                ('status', models.CharField(choices=[('active', 'Обучается'), ('dropped', 'Отчислен'), ('academic_leave', 'Академический отпуск'), ('graduated', 'Выпустился')], default='active', max_length=20, verbose_name='Статус')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.group', verbose_name='Группа')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название дисциплины')),
                ('course', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], verbose_name='Курс')),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2')], verbose_name='Семестр')),
                ('hours', models.PositiveIntegerField(verbose_name='Количество часов')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'unique_together': {('name', 'course', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(choices=[('преподаватель', 'Преподаватель'), ('старший преподаватель', 'Старший преподаватель'), ('доцент', 'Доцент'), ('профессор', 'Профессор'), ('заведующий кафедрой', 'Заведующий кафедрой')], max_length=50, verbose_name='Должность')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.classroom', verbose_name='Закрепленный кабинет')),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Учетная запись')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота')], verbose_name='День недели')),
                ('lesson_number', models.IntegerField(choices=[(1, '1 пара'), (2, '2 пара'), (3, '3 пара'), (4, '4 пара'), (5, '5 пара'), (6, '6 пара')], verbose_name='Номер пары')),
                ('lesson_type', models.CharField(choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная работа'), ('seminar', 'Семинар')], max_length=20, verbose_name='Тип занятия')),
                ('week_type', models.CharField(choices=[('odd', 'Нечетная неделя'), ('even', 'Четная неделя'), ('both', 'Каждую неделю')], default='both', max_length=10, verbose_name='Тип недели')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.classroom', verbose_name='Кабинет')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.group', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['day_of_week', 'lesson_number', 'group'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teacher', verbose_name='Куратор'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('grade_type', models.CharField(choices=[('current', 'Текущая'), ('semester', 'Семестровая'), ('exam', 'Экзамен'), ('credit', 'Зачет')], default='current', max_length=20, verbose_name='Тип оценки')),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')], verbose_name='Семестр')),
                ('date', models.DateField(verbose_name='Дата оценки')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.subject', verbose_name='Дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Преподаватель-дисциплина',
                'verbose_name_plural': 'Преподаватели-дисциплины',
                'unique_together': {('teacher', 'subject')},
            },
        ),
    ]
