# Generated by Django 5.1.2 on 2024-11-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zhizhileva_tour_firm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_seats',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
