# Generated by Django 5.1.2 on 2024-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zhizhileva_tour_firm', '0002_booking_number_of_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='touragency',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
