# Generated by Django 5.1.2 on 2024-11-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zhizhileva_tour_firm', '0003_touragency_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touragency',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
