# Generated by Django 5.1.3 on 2024-11-14 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_second_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_car', to='project_second_app.owner'),
        ),
    ]
