# Generated by Django 5.1.3 on 2024-11-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_second_app', '0002_alter_ownership_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlicense',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='car_id',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
