site_name: Лабораторные работы
nav:
 - Home: index.md
 - 1 лаба:
   - 1 задание: Lr1/1.md
   - 2 задание: Lr1/2.md
   - 3 задание: Lr1/3.md
   - 4 задание: Lr1/4.md
   - 5 задание: Lr1/5.md
theme:
 name: cinder