site_name: Отчет к лабораторным работам по курсу "WEB-пограммирование"
nav:
 - Краткая информация о лабораторных работах: index.md
 - Лабораторная работа №1:
   - Задание 1: 1/task1.md
   - Задание 2: 1/task2.md
   - Задание 3: 1/task3.md
   - Задание 4: 1/task4.md
theme:
 name: bootstrap386