# Generated by Django 5.1.3 on 2024-11-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_library_app", "0002_book_is_discarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="booktransaction",
            name="returned",
            field=models.BooleanField(default=False),
        ),
    ]
