# Generated by Django 5.1.3 on 2024-11-25 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_plate",
                    models.CharField(max_length=15, verbose_name="Гос. номер"),
                ),
                ("brand", models.CharField(max_length=20, verbose_name="Марка")),
                ("model", models.CharField(max_length=20, verbose_name="Модель")),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="Неизвестно",
                        max_length=30,
                        verbose_name="Цвет",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.CharField(max_length=30, verbose_name="Фамилия")),
                ("first_name", models.CharField(max_length=30, verbose_name="Имя")),
                (
                    "birth_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DriverLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(max_length=10, verbose_name="Номер удостоверения"),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("A", "Мотоциклы"),
                            ("A1", "Легкие мотоциклы"),
                            ("B", "Легковые автомобили"),
                            ("B1", "Трициклы и квадрициклы"),
                            ("C", "Грузовые автомобили"),
                            ("C1", "Небольшие грузовые автомобили (3.5-7.5 тонн)"),
                            ("D", "Автобусы"),
                            ("D1", "Небольшие автобусы (8-16 пассажиров)"),
                            ("BE", "Легковые автомобили с прицепами"),
                            ("CE", "Грузовые автомобили с прицепами"),
                            ("DE", "Автобусы с прицепами"),
                            ("M", "Мопеды и скутеры"),
                            ("Tm", "Трамваи"),
                            ("Tb", "Троллейбусы"),
                        ],
                        max_length=4,
                        verbose_name="Категория",
                    ),
                ),
                ("issue_date", models.DateTimeField(verbose_name="Дата выдачи")),
                (
                    "car_owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_license",
                        to="project_first_app.carowner",
                        verbose_name="Владелец",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ownership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(verbose_name="Дата начала владения"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания владения"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_first_app.car",
                        verbose_name="Автомобиль",
                    ),
                ),
                (
                    "car_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="project_first_app.carowner",
                        verbose_name="Владелец",
                    ),
                ),
            ],
        ),
    ]
