# Generated by Django 5.1.3 on 2024-11-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_owner",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.carowner"
            ),
        ),
        migrations.AddField(
            model_name="carowner",
            name="cars",
            field=models.ManyToManyField(
                through="project_first_app.Ownership", to="project_first_app.car"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="brand",
            field=models.CharField(max_length=64, verbose_name="Марка"),
        ),
        migrations.AlterField(
            model_name="car",
            name="color",
            field=models.CharField(
                blank=True, default="Неизвестно", max_length=32, verbose_name="Цвет"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=64, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="carowner",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="carowner",
            name="first_name",
            field=models.CharField(max_length=128, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="carowner",
            name="last_name",
            field=models.CharField(max_length=128, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="issue_date",
            field=models.DateField(verbose_name="Дата выдачи"),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания владения"
            ),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="start_date",
            field=models.DateField(verbose_name="Дата начала владения"),
        ),
    ]
