# Generated by Django 5.1.3 on 2024-11-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_first_app",
            "0002_car_car_owner_carowner_cars_alter_car_brand_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carowner",
            name="cars",
        ),
        migrations.AlterField(
            model_name="car",
            name="car_owner",
            field=models.ManyToManyField(
                related_name="cars",
                through="project_first_app.Ownership",
                to="project_first_app.carowner",
            ),
        ),
    ]
