# Generated by Django 5.1.7 on 2025-03-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0003_remove_user_name_remove_user_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentationregistration',
            name='recommended_for_publication',
            field=models.CharField(choices=[('recommended', 'Рекомендован к публикации'), ('not_recommended', 'Не рекомендован к публикации'), ('pending', 'На рассмотрении')], default='pending', max_length=20, verbose_name='Рекомендация к публикации'),
        ),
    ]
