# Generated by Django 5.1.2 on 2024-11-01 20:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Номер рейса должен состоять из 4 цифр', regex='^\\d{4}$')], verbose_name='Номер рейса')),
                ('airline', models.CharField(max_length=255, verbose_name='Авиакомпания')),
                ('departure_datetime', models.DateTimeField(verbose_name='Дата и время отлета')),
                ('arrival_datetime', models.DateTimeField(verbose_name='Дата и время прилета')),
                ('gate_number', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Номер гейта должен быть 1 буква и 1 цифра', regex='^[A-ZА-Я]\\d$')], verbose_name='Номер гейта')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('passport_number', models.CharField(max_length=5, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(message='Номер паспорта должен состоять из 5 цифр', regex='^\\d{5}$')])),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Номер бронирования должен состоять из 3 цифр', regex='^\\d{3}$')], verbose_name='Номер бронирования')),
                ('ticket_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер билета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights_app.flight', verbose_name='Рейс')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(help_text='Рейтинг от 0 до 10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights_app.booking', verbose_name='Бронирование')),
            ],
        ),
    ]
