# Generated by Django 5.1.5 on 2025-02-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='modified_by',
        ),
    ]
