# Generated by Django 5.1.5 on 2025-01-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, verbose_name='Номер почтового отделения')),
                ('address', models.TextField(verbose_name='Адрес почтового отделения')),
            ],
        ),
        migrations.CreateModel(
            name='PrintShop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название типографии')),
                ('address', models.TextField(verbose_name='Адрес типографии')),
                ('is_open', models.BooleanField(default=True, verbose_name='Типография открыта')),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название газеты')),
                ('index', models.CharField(max_length=50, verbose_name='Индекс издания')),
                ('price', models.FloatField(verbose_name='Цена экземпляра газеты')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='newspapers.editor', verbose_name='Редактор')),
            ],
        ),
        migrations.CreateModel(
            name='PrintRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Тираж')),
                ('date', models.DateField(verbose_name='Дата печати')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_runs', to='newspapers.newspaper', verbose_name='Газета')),
                ('printshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_runs', to='newspapers.printshop', verbose_name='Типография')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество экземпляров')),
                ('post_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newspapers.postoffice', verbose_name='Почтовое отделение')),
                ('print_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newspapers.printrun', verbose_name='Тираж')),
                ('printshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='newspapers.printshop', verbose_name='Типография')),
            ],
        ),
    ]
