# Generated by Django 5.1.3 on 2024-12-02 18:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=10, unique=True, verbose_name='Номер паспорта')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('city_from', models.CharField(max_length=50, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=10, unique=True, verbose_name='Номер паспорта')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название должности')),
                ('salary', models.PositiveIntegerField(verbose_name='Оклад')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер комнаты')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Свободен'), ('OCCUPIED', 'Занят'), ('REQUIRES_CLEANING', 'Требуется уборка'), ('CLEANING_IN_PROGRESS', 'Уборка в процессе'), ('MAINTENANCE', 'На обслуживании')], default='AVAILABLE', max_length=20, verbose_name='Статус комнаты')),
                ('phone', models.CharField(max_length=11, verbose_name='Телефон в номере')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название типа номера')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество мест')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Бесплатный Wi-Fi')),
                ('has_tea_station', models.BooleanField(default=False, verbose_name='Чайная станция')),
                ('has_coffee_machine', models.BooleanField(default=False, verbose_name='Кофемашина')),
                ('has_iron_board', models.BooleanField(default=False, verbose_name='Утюг и гладильная доска')),
                ('has_safe', models.BooleanField(default=False, verbose_name='Сейф в номере')),
                ('has_hair_dryer', models.BooleanField(default=False, verbose_name='Фен')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Телевизор с плоским экраном')),
                ('has_air_conditioning', models.BooleanField(default=False, verbose_name='Система кондиционирования')),
                ('has_bathrobe_slippers', models.BooleanField(default=False, verbose_name='Халат и тапочки')),
                ('has_balcony', models.BooleanField(default=False, verbose_name='Балкон')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('FIXED_TERM', 'Срочный'), ('PERMANENT', 'Бессрочный'), ('CIVIL_CONTRACT', 'ГПХ')], max_length=14, verbose_name='Тип контракта')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Дата расторжения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный контракт')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.employee', verbose_name='Сотрудник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.employeeposition', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата бронирования')),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления')),
                ('arrival_date', models.DateField(verbose_name='Дата заселения')),
                ('departure_date', models.DateField(verbose_name='Дата выселения')),
                ('status', models.CharField(choices=[('BOOKED', 'Забронирован'), ('CONFIRMED', 'Подтвержден'), ('CHECKED_IN', 'Заселен'), ('CHECKED_OUT', 'Выселен'), ('CANCELLED', 'Отменен')], default='BOOKED', max_length=11, verbose_name='Статус состояния')),
                ('payment_status', models.CharField(choices=[('PREPAID', 'Предоплата'), ('PAID', 'Оплачен'), ('UNPAID', 'Не оплачен'), ('REFUNDED', 'Возврат')], default='UNPAID', max_length=8, verbose_name='Статус оплаты')),
                ('price_at_booking', models.PositiveIntegerField(verbose_name='Стоимость при бронировании')),
                ('final_price', models.PositiveIntegerField(verbose_name='Стоимость при бронировании')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='Администратор')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.client', verbose_name='Клиент')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновивший администратор')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_date', models.DateField(verbose_name='Дата уборки')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидается'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершена')], default='PENDING', max_length=11, verbose_name='Статус уборки')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.employmentcontract', verbose_name='Сотрудник')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.room', verbose_name='Комната')),
            ],
        ),
        migrations.CreateModel(
            name='RoomPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало действия цены')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец действия цены')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость за сутки')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.roomtype', verbose_name='Тип номера')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.roomtype', verbose_name='Тип комнаты'),
        ),
    ]
