# Generated by Django 5.1.2 on 2024-12-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
    ]
