# Generated by Django 3.2 on 2025-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tour',
            name='payment_terms',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='touragency',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]