# Generated by Django 5.1.6 on 2025-03-14 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales_agency_app", "0002_client_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="user",
        ),
    ]
