# Generated by Django 5.1.4 on 2024-12-18 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokerinfo",
            name="broker",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="app.broker"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="brokerinfo",
            name="broker_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.brokercompany",
            ),
        ),
    ]
