# Generated by Django 5.1.4 on 2024-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_brokerinfo_broker_alter_brokerinfo_broker_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expiry_period",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
