# Generated by Django 5.1.4 on 2024-12-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_product_expiry_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("op", "Opened"),
                    ("cr", "Created"),
                    ("c", "Canceled"),
                    ("p", "Paid"),
                    ("d", "Delivered"),
                ],
                default="op",
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
