# Generated by Django 5.1.4 on 2024-12-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="prepaid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("op", "Opened"),
                    ("cr", "Created"),
                    ("c", "Canceled"),
                    ("p", "Paid"),
                    ("d", "Delivered"),
                ],
                default="op",
                max_length=5,
            ),
        ),
    ]
