# Generated by Django 5.1.4 on 2024-12-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_order_delivery_date_alter_order_prepaid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("op", "Opened"), ("p", "Paid"), ("d", "Delivered")],
                default="op",
                max_length=5,
            ),
        ),
    ]
