# Generated by Django 5.1.4 on 2024-12-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("op", "Opened"),
                    ("cr", "Created"),
                    ("p", "Paid"),
                    ("d", "Delivered"),
                ],
                default="op",
                max_length=5,
            ),
        ),
    ]
