# Generated by Django 5.1.3 on 2024-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carowner",
            name="cars",
            field=models.ManyToManyField(
                through="hotels_project.Ownership", to="hotels_project.car"
            ),
        ),
    ]
