# Generated by Django 5.1.3 on 2024-11-23 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hotels_project",
            "0003_alter_carowner_options_alter_carowner_managers_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="carowner",
            name="birthday_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="owner_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
