# Generated by Django 5.2.7 on 2025-10-20 16:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель автомобиля')),
                ('car_class', models.CharField(choices=[('F1', 'Формула-1'), ('GT', 'Гран-туризмо'), ('Rally', 'Ралли'), ('Endurance', 'Эндуранс'), ('Drift', 'Дрифт')], max_length=20, verbose_name='Класс автомобиля')),
                ('engine', models.CharField(max_length=100, verbose_name='Двигатель')),
                ('horsepower', models.IntegerField(verbose_name='Лошадиные силы')),
                ('description', models.TextField(blank=True, verbose_name='Описание автомобиля')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название гонки')),
                ('race_type', models.CharField(choices=[('Qualifying', 'Квалификация'), ('Sprint', 'Спринт'), ('Main', 'Основная гонка'), ('Championship', 'Чемпионат')], max_length=20, verbose_name='Тип гонки')),
                ('location', models.CharField(max_length=100, verbose_name='Место проведения')),
                ('start_date', models.DateTimeField(verbose_name='Дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата и время окончания')),
                ('description', models.TextField(blank=True, verbose_name='Описание гонки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активная гонка')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('description', models.TextField(blank=True, verbose_name='Описание команды')),
                ('founded_date', models.DateField(verbose_name='Дата основания')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Логотип')),
            ],
        ),
        migrations.CreateModel(
            name='RacingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Опыт вождения (лет)')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('comment_type', models.CharField(choices=[('cooperation', 'Вопрос о сотрудничестве'), ('racing', 'Вопрос о гонках'), ('other', 'Иное')], max_length=20, verbose_name='Тип комментария')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг (1-10)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.race', verbose_name='Гонка')),
            ],
        ),
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('racer_class', models.CharField(choices=[('Pro', 'Профессионал'), ('Semi-pro', 'Полупрофессионал'), ('Amateur', 'Любитель'), ('Rookie', 'Новичок')], max_length=20, verbose_name='Класс гонщика')),
                ('license_number', models.CharField(max_length=20, unique=True, verbose_name='Номер лицензии')),
                ('wins_count', models.IntegerField(default=0, verbose_name='Количество побед')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='racing_app.team', verbose_name='Команда')),
            ],
        ),
        migrations.CreateModel(
            name='RaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждена')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.car', verbose_name='Автомобиль')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.race', verbose_name='Гонка')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.racer', verbose_name='Гонщик')),
            ],
            options={
                'unique_together': {('racer', 'race')},
            },
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish_time', models.DurationField(blank=True, null=True, verbose_name='Время финиша')),
                ('position', models.IntegerField(blank=True, null=True, verbose_name='Позиция')),
                ('best_lap_time', models.DurationField(blank=True, null=True, verbose_name='Лучшее время круга')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('dnf', models.BooleanField(default=False, verbose_name='Не финишировал')),
                ('race_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='racing_app.raceregistration', verbose_name='Регистрация')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racing_app.team', verbose_name='Команда'),
        ),
    ]
