# Generated by Django 5.1.6 on 2025-02-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registration",
            name="confirmed",
        ),
        migrations.AddField(
            model_name="speaker",
            name="approved",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
