# Generated by Django 5.1.6 on 2025-02-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0002_remove_registration_confirmed_speaker_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
