# Generated by Django 5.1.6 on 2025-02-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0003_speaker_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="registration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="conferences.registration",
            ),
        ),
    ]
