/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CleaningSchedule: typeof import('./components/CleaningSchedule.vue')['default']
    ClientsPage: typeof import('./components/ClientsPage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    HotelReportPage: typeof import('./components/HotelReportPage.vue')['default']
    LoginPage: typeof import('./components/LoginPage.vue')['default']
    RegisterPage: typeof import('./components/RegisterPage.vue')['default']
    ReservationPage: typeof import('./components/ReservationPage.vue')['default']
    RoomInfoPage: typeof import('./components/RoomInfoPage.vue')['default']
    RoomsPage: typeof import('./components/RoomsPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffPage: typeof import('./components/StaffPage.vue')['default']
  }
}
