# Generated by Django 4.2.19 on 2025-02-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
