# Generated by Django 4.2.19 on 2025-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_alter_carowner_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlicense',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='start_date',
            field=models.DateField(),
        ),
    ]
