# Generated by Django 5.1.2 on 2024-11-02 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0002_submission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="grade",
        ),
        migrations.AlterField(
            model_name="submission",
            name="hw",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="project_first_app.homework",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студент",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submission_text",
            field=models.TextField(verbose_name="Ответ"),
        ),
    ]
