# Generated by Django 5.1.2 on 2024-11-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_first_app",
            "0003_remove_homework_grade_alter_submission_hw_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="grade",
            field=models.IntegerField(blank=True, null=True, verbose_name="Оценка"),
        ),
    ]
