# Generated by Django 5.1.2 on 2024-11-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_first_app", "0004_submission_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="subject",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Предмет"
            ),
        ),
    ]
