# Generated by Django 5.2.7 on 2025-10-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
