# Generated by Django 5.2.7 on 2025-10-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotels.amenity'),
        ),
    ]
