site_name: WEB-programming
site_url: https://owarpero.github.io/ITMO_ICT_WebDevelopment_2024-2025/
nav:
  - Home: index.md
  - 1 lab:
      - Task 1: lab1/1.md
      - Task 2: lab1/2.md
      - Task 3: lab1/3.md
      - Task 4: lab1/4.md
      - Task 5: lab1/5.md
      - Notes: lab1/notes.md
  - 2 lab:
      - Task: lab2/1.md
  - 3 lab:
      - Task: lab3/1.md
  - 4 lab:
      - Task: lab4/1.md
  - practical_work:
      - 3.1: practical_work/3.1.md
theme:
  name: readthedocs
