# Generated by Django 5.1.4 on 2024-12-26 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participationcondition",
            name="conference",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="conferences.conference"
            ),
        ),
    ]
