# Generated by Django 5.1.4 on 2024-12-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conferences", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(default="Test", max_length=30),
            preserve_default=False,
        ),
    ]
