# Generated by Django 5.1.4 on 2025-01-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_num", models.CharField(max_length=20, unique=True)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("VS", "Особо малый"),
                            ("S", "Малый"),
                            ("M", "Средний"),
                            ("L", "Большой"),
                            ("VL", "Особо большой"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=40, verbose_name="ФИО")),
                (
                    "passport",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Паспортные данные"
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(verbose_name="Стаж работы в годах"),
                ),
                (
                    "driver_category",
                    models.CharField(
                        choices=[
                            ("A", "Обычный автобус"),
                            ("B", "Электробус"),
                            ("C", "Туристический автобус"),
                            ("D", "Грузовой автобус"),
                        ],
                        max_length=10,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Зарплата"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_num", models.CharField(max_length=20, unique=True)),
                ("start_point", models.CharField(max_length=100)),
                ("end_point", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("interval", models.PositiveIntegerField()),
                ("duration", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("accident", "Accident"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField()),
                ("shift_start", models.TimeField()),
                ("shift_end", models.TimeField()),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bus_app.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bus_app.busdriver",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="bus_app.route",
                    ),
                ),
            ],
        ),
    ]
