# Generated by Django 4.2.16 on 2024-11-27 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='Номер паспорта')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
                ('city_of_origin', models.CharField(max_length=100, verbose_name='Город прибытия')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Одноместный'), ('DOUBLE', 'Двухместный'), ('TRIPLE', 'Трехместный')], max_length=10, verbose_name='Тип номера')),
                ('cost_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость за день')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('is_available', models.BooleanField(default=True, verbose_name='Свободен')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Отчество')),
            ],
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('stay_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='administrator.client', verbose_name='Клиент')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stays', to='administrator.room', verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningSchedule',
            fields=[
                ('cleaning_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('time_and_day_of_week', models.CharField(max_length=50, verbose_name='Время и день недели')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_schedules', to='administrator.room', verbose_name='Номер')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_schedules', to='administrator.staff', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='CleaningExecution',
            fields=[
                ('cleaning_execution_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_and_day_of_week', models.CharField(max_length=50, verbose_name='Время и день недели')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('cleaning_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='administrator.cleaningschedule', verbose_name='Расписание уборки')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleaning_executions', to='administrator.room', verbose_name='Номер')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_executions', to='administrator.staff', verbose_name='Сотрудник')),
            ],
        ),
    ]
