# Generated by Django 5.1.4 on 2025-01-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='check_out_date',
        ),
    ]
