# Generated by Django 5.2.6 on 2025-11-03 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите название удобства (например, Wi-Fi, Кондиционер)', max_length=100, unique=True, verbose_name='Название удобства')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите тип номера (например, Люкс, Стандарт)', max_length=100, unique=True, verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Укажите полное название отеля', max_length=200, verbose_name='Название отеля')),
                ('address', models.CharField(help_text='Полный адрес отеля', max_length=300, verbose_name='Адрес')),
                ('description', models.TextField(blank=True, help_text='Подробное описание отеля', verbose_name='Описание')),
                ('amenities', models.ManyToManyField(blank=True, help_text='Выберите все доступные удобства в отеле', related_name='hotels', to='hotel_app.amenity', verbose_name='Удобства')),
                ('owner', models.ForeignKey(blank=True, help_text='Владелец или управляющий отеля', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_hotels', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Стоимость проживания за одну ночь', max_digits=10, verbose_name='Цена за ночь')),
                ('capacity', models.PositiveIntegerField(help_text='Максимальное количество гостей', verbose_name='Вместимость')),
                ('is_active', models.BooleanField(default=True, help_text='Отключите, если номер временно недоступен для бронирования', verbose_name='Активен')),
                ('amenities', models.ManyToManyField(blank=True, help_text='Выберите доступные удобства в номере', related_name='rooms', to='hotel_app.amenity', verbose_name='Удобства')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_app.hotel', verbose_name='Отель')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hotel_app.roomtype', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
                'ordering': ['hotel__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_from', models.DateField(help_text='Дата начала проживания', verbose_name='Дата заезда')),
                ('stay_to', models.DateField(help_text='Дата окончания проживания', verbose_name='Дата выезда')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оцените номер от 1 до 10', validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1'), django.core.validators.MaxValueValidator(10, message='Рейтинг не может быть больше 10')], verbose_name='Оценка')),
                ('text', models.TextField(help_text='Поделитесь своими впечатлениями о проживании', verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hotel_app.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(help_text='Дата начала проживания', verbose_name='Дата заезда')),
                ('check_out', models.DateField(help_text='Дата окончания проживания', verbose_name='Дата выезда')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('CONFIRMED', 'Подтверждено'), ('CHECKED_IN', 'Заселен'), ('CHECKED_OUT', 'Выселен'), ('CANCELLED', 'Отменено')], default='PENDING', help_text='Текущий статус бронирования', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel_app.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='hotel_app_h_name_121c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['owner'], name='hotel_app_h_owner_i_928b95_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['room', 'rating'], name='hotel_app_r_room_id_a8a47d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', 'room'], name='hotel_app_r_user_id_05ff94_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'check_in', 'check_out'], name='hotel_app_r_room_id_9dfaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='hotel_app_r_user_id_c8c735_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'check_in'], name='hotel_app_r_status_faced4_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'is_active'], name='hotel_app_r_hotel_i_3cf7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night'], name='hotel_app_r_price_p_c9e53c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'id')},
        ),
    ]
