# Generated by Django 5.1.3 on 2024-12-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chicken_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborcontract',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('p', 'paused'), ('f', 'fired'), ('e', 'expired')], max_length=1),
        ),
    ]
