# Generated by Django 5.1.2 on 2024-11-13 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='drf_project.autoowner'),
        ),
    ]
