# Generated by Django 5.1.3 on 2024-12-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_homework_issue_date_alter_homework_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='old_teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assignments.teacher'),
        ),
    ]
