# Generated by Django 5.1.3 on 2024-12-03 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_homework_old_teacher_alter_homework_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='old_teacher',
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assignments.teacher'),
        ),
    ]
