# Generated by Django 5.1.3 on 2024-11-30 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='ФИО редактора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления редактора')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления информации')),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('office_number', models.PositiveIntegerField(verbose_name='Номер почтового отделения')),
                ('address', models.TextField(verbose_name='Адрес почтового отделения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления почтового отделения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления информации')),
            ],
        ),
        migrations.CreateModel(
            name='PrintShop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название типографии')),
                ('address', models.TextField(verbose_name='Адрес типографии')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Статус закрытия типографии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления типографии')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления информации')),
            ],
        ),
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название газеты')),
                ('index', models.CharField(max_length=50, verbose_name='Индекс издания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена экземпляра газеты')),
                ('price_updated_at', models.DateTimeField(verbose_name='Дата последнего изменения цены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления газеты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления информации')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='newspapers.editor', verbose_name='Редактор')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('copies_printed', models.PositiveIntegerField(verbose_name='Тираж газеты в типографии')),
                ('copies_sent', models.PositiveIntegerField(verbose_name='Количество экземпляров, отправленных в почтовое отделение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления информации')),
                ('newspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='newspapers.newspaper', verbose_name='Газета')),
                ('postoffice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='newspapers.postoffice', verbose_name='Почтовое отделение')),
                ('printshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='newspapers.printshop', verbose_name='Типография')),
            ],
        ),
    ]
