# Generated by Django 5.1.2 on 2024-10-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_comment_race_alter_registration_race_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racer',
            name='car',
        ),
        migrations.AddField(
            model_name='racer',
            name='cars',
            field=models.ManyToManyField(blank=True, related_name='racers', to='races.automobile'),
        ),
    ]
