# Generated by Django 5.1.2 on 2024-10-29 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_remove_racer_car_racer_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='races.automobile'),
        ),
    ]
