# Generated by Django 5.1.2 on 2024-11-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_registration_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='races.automobile'),
        ),
    ]
