# Generated by Django 5.1.2 on 2024-11-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_first_app', '0002_carowner_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='nationality',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='carowner',
            name='passport',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
