# Generated by Django 5.1.3 on 2024-12-24 23:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('egg_performance_avg', models.IntegerField()),
                ('weight_avg', models.FloatField(validators=[django.core.validators.MinValueValidator(1.5), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cell_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('season', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=50)),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chicken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(1.5), django.core.validators.MaxValueValidator(5.0)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('egg_performance_month', models.IntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_app.breed')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_app.cell')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='diet_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_app.diet'),
        ),
        migrations.CreateModel(
            name='LaborContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('f', 'full-time'), ('p', 'part-time')], max_length=1)),
                ('status', models.CharField(choices=[('a', 'active'), ('p', 'paused'), ('f', 'fired')], max_length=1)),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(5000), django.core.validators.MaxValueValidator(100000)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_app.cell')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chicken_app.workshop'),
        ),
    ]
