# Generated by Django 5.1.2 on 2024-11-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tour", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
