# Generated by Django 5.1.2 on 2024-11-20 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carowner',
            name='cars',
            field=models.ManyToManyField(related_name='owners', through='cars.Ownership', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='car_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='cars.carowner'),
        ),
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=10)),
                ('license_type', models.CharField(choices=[('A', 'Motorcycle'), ('B', 'Passenger car'), ('C', 'Truck')], max_length=1)),
                ('issue_date', models.DateField()),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='cars.carowner')),
            ],
        ),
        migrations.DeleteModel(
            name='DrivingLicence',
        ),
    ]
