# Generated by Django 4.2.20 on 2025-03-10 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО')),
                ('driver_class', models.CharField(choices=[('I', 'I класс'), ('II', 'II класс'), ('III', 'III класс')], max_length=3)),
                ('experience', models.PositiveSmallIntegerField(help_text='Стаж работы в годах')),
                ('birth_date', models.DateField()),
                ('hire_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_number', models.CharField(max_length=20, unique=True)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interval_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buspark.buscategory')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Active', 'Отработано'), ('Breakdown', 'Поломка автобуса'), ('No Driver', 'Нет водителя')], default='Active', max_length=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buspark.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buspark.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buspark.route')),
            ],
            options={
                'unique_together': {('driver', 'shift_date', 'start_time', 'end_time')},
            },
        ),
    ]
