# Generated by Django 4.2.20 on 2025-03-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buspark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Автобус', 'verbose_name_plural': 'Автобусы'},
        ),
        migrations.AlterModelOptions(
            name='buscategory',
            options={'verbose_name': 'Тип автобуса', 'verbose_name_plural': 'Типы автобусов'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': 'Смена', 'verbose_name_plural': 'Смены'},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='hire_date',
        ),
    ]
