# Generated by Django 4.2.20 on 2025-03-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buspark', '0002_alter_bus_options_alter_buscategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buspark.bus'),
            preserve_default=False,
        ),
    ]
