# Generated by Django 5.1.3 on 2024-11-27 14:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                ("id_room", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Оборудованная", "Оборудованная"),
                            ("Базовая", "Базовая"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id_student", models.AutoField(primary_key=True, serialize=False)),
                ("surname", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[("М", "Мужской"), ("Ж", "Женский")], max_length=1
                    ),
                ),
                ("class_name", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id_lesson", models.AutoField(primary_key=True, serialize=False)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Понедельник", "Понедельник"),
                            ("Вторник", "Вторник"),
                            ("Среда", "Среда"),
                            ("Четверг", "Четверг"),
                            ("Пятница", "Пятница"),
                            ("Суббота", "Суббота"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lesson_number",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                        ],
                        max_length=2,
                    ),
                ),
                ("subject", models.CharField(max_length=20)),
                ("class_label", models.CharField(max_length=3)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="school_app.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                ("id_grade", models.AutoField(primary_key=True, serialize=False)),
                ("subject", models.CharField(max_length=30)),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ]
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSchedule",
            fields=[
                ("id_schedule", models.AutoField(primary_key=True, serialize=False)),
                ("lessons", models.ManyToManyField(to="school_app.lesson")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="school_app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("id_teacher", models.AutoField(primary_key=True, serialize=False)),
                ("surname", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=20)),
                (
                    "lessons",
                    models.ManyToManyField(
                        blank=True, related_name="taught_by", to="school_app.lesson"
                    ),
                ),
                (
                    "room_assigned",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_teachers",
                        to="school_app.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="teacher",
            field=models.ManyToManyField(
                blank=True, related_name="rooms", to="school_app.teacher"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaches",
                to="school_app.teacher",
            ),
        ),
    ]
