site_name: My Docs
nav:
  - Home: index.md
  - Lab №1:
    - Task 1: lr1/task1.md
    - Task 2: lr1/task2.md
    - Task 3: lr1/task3.md
    - Task 4: lr1/task4.md
    - Task 5: lr1/task5.md
  - Lab №2:
    - Models: lr2/models.md
    - Views: lr2/views.md
    - Navigation: lr2/router.md
  - Lab №3:
    - PR 1: lr3/practice1.md
    - PR 2: lr3/practice2.md
    - PR 3: lr3/practice3.md
    - About: lr3/about.md
    - Models: lr3/models.md
    - Auth/Register: lr3/auth.md
    - API: lr3/api.md

theme:
 name: material