site_name: WEB-programming
nav:
    - Home: index.md
    - 1 lab:
      - Task 1: laboratory_work_1/1.md
      - Task 2: laboratory_work_1/2.md
      - Task 3: laboratory_work_1/3.md
      - Task 4: laboratory_work_1/4.md
      - Task 5: laboratory_work_1/5.md
theme:
    name: readthedocs