site_name: Web documentation
docs_dir: docs

nav:
  - Home: index.md
  - Lab 1:
      - "Task 1": Lr1/task1.md
      - "Task 2": Lr1/task2.md
      - "Task 3": Lr1/task3.md
      - "Task 4": Lr1/task4.md
      - "Task 5": Lr1/task5.md

  - Lab 2:
      - "Pract 1": Lr2/practtask1.md
      - "Pract 2": Lr2/practtask2.md
      - "Pract 3": Lr2/practtask3.md
      - "Lab 2": Lr2/task.md


theme:
  name: material