# Generated by Django 5.1.4 on 2025-01-09 00:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя тренера')),
                ('last_name', models.TextField(max_length=50, verbose_name='Фамилия тренера')),
                ('middle_name', models.TextField(max_length=50, verbose_name='Отчество тренера')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Пол тренера')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения тренера')),
                ('qualification', models.TextField(max_length=100, verbose_name='Квалификация')),
                ('experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Опыт работы')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(choices=[('t', 'team'), ('i', 'individual')], max_length=1, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='Sportsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя спортсмена')),
                ('last_name', models.TextField(max_length=50, verbose_name='Фамилия спортсмена')),
                ('middle_name', models.TextField(max_length=50, verbose_name='Отчество спортсмена')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=1, verbose_name='Пол спортсмена')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения спортсмена')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='SportHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название зала')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('sport', models.ManyToManyField(to='sport_center_backend.sport', verbose_name='Вид спорта')),
            ],
        ),
        migrations.CreateModel(
            name='SportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Наименование')),
                ('description', models.TextField(max_length=100, verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Вместимость группы')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_backend.sport', verbose_name='Вид спорта')),
                ('sportsmen', models.ManyToManyField(to='sport_center_backend.sportsman', verbose_name='Спортсмены')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.TextField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=15, verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('sport_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_backend.sporthall', verbose_name='Зал')),
                ('sport_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_backend.sportsection', verbose_name='Секция')),
            ],
        ),
        migrations.CreateModel(
            name='SportSectionCoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Принят на должность')),
                ('end', models.DateField(null=True, verbose_name='Уволен с должности')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_backend.coach', verbose_name='Тренер')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_center_backend.sportsection', verbose_name='Секция')),
            ],
        ),
    ]
